### ISSUE TITLE
Processes go haywire with tombo resquiggle

### ISSUE THREAD

**Issue by kehey** [nanoporetech/tombo#101]
Hi,

I'm hitting strange behaviour where running Tombo with any setting of --processes takes up to 20 cores of my machine. Does not matter whether I run it locally, or submit it onto a HPC cluster (as verified in both cases with htop).

I've also tried setting the threads per process to 1 in addition to processes 1 (although both are default anyway) to no avail.

Tombo shows the same behaviour in version 1.3 as in version 1.4.

The result is fine, so it actually did it's job, but to use this in bulk on an HPC, I really need to be in control of the processes. My gut feeling says it might be more related to mappy processes but I don't know whether we can control those?

Any idea what could be going on?

**Comment by marcus1487** [comment]
I think your instinct that this is a mappy issue is probably correct, but I have not seen this level of usage. I have not kept a close eye when running on large genomes, so that may be increasing the thread/core usage of mappy. 

I can confirm that tombo resquiggle with --processes and --threads-per-process both set to 1 will have 1 mappy Aligner object open and 1 tombo process (that is only active when the mappy thread is locked and visa versus), but it is possible that this is still allows mappy to use many threads.

Can you confirm that the processes are actually using the CPU and not just spawning many workers (that may not be consuming CPU)? Also is this intermittent via htop with a single tombo process using CPU (expected behavior when a read is passed from mapping to re-squiggling; though this may happen too often to see in htop)? I am not sure that the mappy threading can be controlled, but will certainly take a look.

**Comment by kehey** [comment]
I'll look to provide a screenshot when I'm behind my desk. But the way I see it, it is really utilising 20 threads at the same time.

It might also be worth to mention that I already pre-create the minimap index and provide this to tombo instead of the fasta.

**Comment by kehey** [comment]
Interesting workaround: you can actually restrict the whole process to exactly one CPU using the unix command `taskset -c <cpu_id>` as can be found at https://unix.stackexchange.com/questions/23106/how-to-limit-a-process-to-one-cpu-core-in-linux

**Comment by marcus1487** [comment]
Just ran into this on a run, and it looks like setting either `export OMP_NUM_THREADS=1` or `export OPENBLAS_NUM_THREADS=1` constrains each process to only use a single core. I think this is occurring from some of the numpy or cython calls that were compiled with openmp enabled. This should resolve this issue (and potentially increase performance on the requested resources).
