### ISSUE TITLE
Interpretation of dampened fraction result

### ISSUE THREAD

**Issue by BisonKok** [nanoporetech/tombo#102]
Hi. I have a quick question on the dampened fraction. If the dampened fraction value for a particular position is higher, does that mean there is higher chance that this position is modified?

**Comment by marcus1487** [comment]
The dampened fraction effectively adds a pseudo-count to the reads estimated to be modified or un-modified at any positions. These default counts are 2 modified reads and half an un-modified read.

Thus I would interpret a higher dampened fraction than raw fraction as an indication that the confidence that the position is completely unmodified is lower. The dampened fraction should only be significantly higher than the raw fraction (with the defaults) at very low coverage and mostly (if not all) unmodified reads at a location. 

The other option would be to change the default values to 2 and 0 (e.g. set `--coverage-dampen-counts 2 0` option to the `tombo detect_modifications` command). Setting the modified pseudo-count to 0 means that the dampened fraction will never be higher than the raw fraction. The half a modified read gave slightly better performance metrics internally (on a variable coverage sample), and so this was chosen as the default, but this does not mean it is best in all settings.

Hopefully this interpretation makes sense, but do let me know if further explanation would be helpful!

**Comment by BisonKok** [comment]
Does that mean that if the dampened fraction is higher for the specific position, there is more modified reads than the unmodified reads? If I would like to know the modification rate for the specific position, do I have to generate raw fraction for pair wise comparison as well?

**Comment by marcus1487** [comment]
I’m not sure I understand the question here. If you would like the raw fraction of reads estimated to be modified at any position, the fraction output option would be best. The dampened fraction option is intended to make the rank order of fraction values across genomes/samples more reliable over variable depths of coverage (since fraction of modified reads is an unreliable statistic for low coverage). So higher dampened fractions should generally represent higher fractions of modified bases, but there are likely edge cases where specific examples of dampened fractions may be slightly misleading. I realize this might be s but confusing, but hopefully this helps a bit.
