### ISSUE TITLE
plotting  pronlems

### ISSUE THREAD

**Issue by chen318liang** [nanoporetech/tombo#109]
hello, when I use command "tombo plot most_significant --fast5-basedirs /data2/mayue/chenl/nanopore/20180822_0953_E_coli_13h_fast5/fast5/pass \
    --statistics-filename sample.alt_modified_base_detection.6mA.tombo.stats \
    --plot-standard-model --plot-alternate-model 6mA \
    --pdf-filename sample.most_significant_6mA_sites.pdf", it produce warnings below and produced a pdf file without content. what is the problem?

[14:51:48] Parsing Tombo index file(s).
[14:51:50] Loading default canonical ***** DNA ***** model.
[14:51:50] Calculating read coverage regions.
[14:51:50] Calculating read coverage.
[14:51:51] Preparing plot data.
******************** WARNING ********************
	Unable to extract data from read. Potentially corrupted file or invalid Tombo index file for this directory.
******************** WARNING ********************
	Unable to extract data from read. Potentially corrupted file or invalid Tombo index file for this directory.
******************** WARNING ********************
	Unable to extract data from read. Potentially corrupted file or invalid Tombo index file for this directory.
.
.
.
******************** WARNING ********************
	Genome resolved raw signal could not be retrieved for some reads. Ensure that reads have been re-squiggled and that all data slot corresponding accordingly.
[14:51:56] Plotting

**Comment by marcus1487** [comment]
This error indicates that a read filename contained in the Tombo index either does not exist in its original location (relative to the base directory passed to the resquiggle command) or the file has been corrupted since processing with the re-squiggle command. I would recommend running the re-squiggle command again to link the read filenames correctly.

**Comment by lfaino** [comment]
Dear marcus
I have the same warning but ends with:

> Genome resolved raw signal could not be retrieved for some reads. Ensure that reads have been re-squiggled with the specified [--corrected-group].


the command that i used is:

`tombo resquiggle fast5/ Fus.contigs.polished.methilated.SRR1609157.sorted.vcf.fasta --processes 16 --dna  --num-most-common-errors 5 --overwrite
 tombo plot max_coverage --fast5-basedirs fast5/ --plot-standard-model`

Any idea where the problem is?

Cheers

Luigi

**Comment by marcus1487** [comment]
This is generally an issue with file access to the fast5 read filenames. Did the resquiggle command complete successfully? And were these commands run one after another in the same environment?
