### ISSUE TITLE
the output of the 'tombo detect_modifications' is not stable

### ISSUE THREAD

**Issue by HuJane** [nanoporetech/tombo#110]
Dear,
I am not sure why the output of the following command is not stable? For each run, the size of stats is different
tombo detect_modifications alternative_model --fast5-basedirs /home/hujie/nanopore/albacore/HJBM-batch2/workspace/pass/ --alternate-bases 6mA --statistics-file-basename HJBM-2-adr
	19971 Sep 14 10:18 HJBM-2-adr.6mA.tombo.stats
	19888 Sep 14 10:18 HJBM-2-adr.6mA.tombo.stats
	19938 Sep 14 10:19 HJBM-2-adr.6mA.tombo.stats
	19954 Sep 14 10:19 HJBM-2-adr.6mA.tombo.stats
	19919 Sep 14 10:19 HJBM-2-adr.6mA.tombo.stats

**Comment by marcus1487** [comment]
The Tombo statistics output is an HDF5 file under the hood, so my best guess here is that the HDF5 chunking grabs a slightly different pattern of memory for each run, possibly based on the order in which the statistics blocks are saved as returned from the multiprocessing jobs. In any case, the testing methods are deterministic and should result in the exact same results. Thus I suspect that these slight memory discrepancies are more of a low level HDF5 memory allocation issue and should not effect the validity of the results.

You may also try a [h5repack](https://support.hdfgroup.org/HDF5/doc/RM/Tools.html#Tools-Repack) call in order to compress the memory footprint for these files (which I think should then be consistent as well).
