### ISSUE TITLE
Outputting list of modified bases 

### ISSUE THREAD

**Issue by Somebodyatthdoor** [nanoporetech/tombo#117]
Hi,

I would like to output as a text file a list of all of the regions which tombo has detected as being modified, from most consistently/significantly modified to least.

Is there a way of doing this in tombo?

Thanks for your help, 
Laura

**Comment by marcus1487** [comment]
The `dampend_fraction` browser output file contains this information ([more info here](https://nanoporetech.github.io/tombo/text_output.html#tombo-text-output-browser-files)).

In order to use this output to create a list the wig format would need to be converted to something like bed format. The `bedops` package contains the [wig2bed command](https://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion/wig2bed.html) which can be used for this purpose. For example in order to obtain a sorted list of the most consistently/significantly modified positions one could run the following command:
```
wig2bed < tombo_output.dampened_fraction_modified_reads.wig | sort -k5,5rn > \ 
    tombo_output.sorted_sites.bed
```

**Comment by marcus1487** [comment]
The other option here would be to use the python API to extract the most significant sites from the intermediate Tombo statistics file. The documentation for this function can be found [here](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_stats.TomboStats.iter_most_signif_sites). For example, this snippet of python code would iterate through the most significantly modified sites:

```
from tombo import tombo_stats
stats = tombo_stats.TomboStats('path/to/tombo/stats/file.tombo.stats')
# pos is 0-based; and docs have a slight error that valid coverage is included in output
for chrm, strand, pos, frac, damp_frac, valid_cov in stats.iter_most_signif_sites():
   # perform analyses
```
