### ISSUE TITLE
Tombo detect modifications does not show progress. Is it working?

### ISSUE THREAD

**Issue by impreza-92** [nanoporetech/tombo#126]
Hello. I want to detect modifications using the model provided with Tombo with the following command:

tombo detect_modifications alternative_model --fast5-basedirs ./pass --statistics-file-basename test --alternate-bases 5mC --processes 16

However, the terminal does not show any progress. It shows this:

[16:34:38] Parsing Tombo index file(s).
[16:34:43] Performing alternative model testing.
[16:34:43] Performing specific alternate base(s) testing.
[16:34:43] Calculating read coverage regions.
[16:34:43] Calculating read coverage.
[16:34:46] Performing modified base detection across genomic regions.
  0%|                                                                                         | 0/10 [00:00<?, ?it/s]

Do I just have to wait or is it perhaps not working? Htop does show that all my cores are being used, though.

**Comment by marcus1487** [comment]
It is likely working. To ensure that this is working, you should see the tombo statistics file (`test.5mC.tombo.stats` in this case) has been created in that directory.

This appears to be a relatively small reference (as there are only 10 iterations indicated to be completed). Each of these 10 iterations is processing one 10kb region in parallel (default for `--multiprocess-region-size` option). Thus you cannot even make use of the requested 16 cores since there are only 10 jobs to be completed for this run. If this is a very high coverage sample processing all reads over a 10kb region may take a lot of processing (and thus little progress is shown).

The first option to see progress would be the `--multiprocess-region-size` option to process smaller chunks.

The other option to complete processing more quickly is to use the `tombo filter level_coverage` command to selectively downsample reads to a lower, but still acceptable level of coverage (this will only effect the tombo index file and can be cleared with the `tombo filter clear_filters` command). You can run the `tombo text_output browser_files` command with the `--file-types coverage` option to get the coverage for the sample and determine a useful value for the `--percent-to-filter` option to the `tombo filter level_coverage` command. Then only the randomly downsampled reads would be processed more quickly.
