### ISSUE TITLE
Question about P values of significant regions

### ISSUE THREAD

**Issue by weir12** [nanoporetech/tombo#129]
Hi:
  I have some confusion about the P values in `tombo_results.significant_regions.fasta` file which was extracted  from `sample.level_compare_sample.tombo.stats` 
  Here's example of P values:
```
>AT1G07320.1:521:+ -log10(p-value): 1.3
TACTGCTTCCACACT
>AT5G10840.1:2174:+ -log10(p-value): 0.8
CAAAAGAGATTTTAA
>AT5G16390.1:1199:+ -log10(p-value): 0.79
TTGCTGAGACTTCTA
>AT1G32500.1:1754:+ -log10(p-value): 0.75
TTAATTAAAAACTAA
>AT5G13450.1:1016:+ -log10(p-value): 0.74
TTTTCGAGACATCAA
>AT5G27470.1:1597:+ -log10(p-value): 0.72
TTTTTTGGACTTCTG
>AT5G27850.2:865:+ -log10(p-value): 0.71
TTCTCAAGACAATTG
>AT1G03475.1:1481:+ -log10(p-value): 0.69
CAATGAAGACAAACT
>AT4G21860.4:774:+ -log10(p-value): 0.68
TTCTGTGAGACTAAT
>AT2G36170.1:533:+ -log10(p-value): 0.68
TGAGAAAGACTCCTC
>AT2G27730.1:673:+ -log10(p-value): 0.68
CTTGTGAGACACTTT
>AT4G16720.1:805:+ -log10(p-value): 0.67
```
I have noticed that all of these P values(except the first one) are greater than 0.05.Does that mean there isn't Significantly modified position in provided two sample detected by  level_sample_compare method?

**Comment by marcus1487** [comment]
Yes. At the 0.05 significance level this output (assuming this is the very beginning of the fasta file) indicates that there are no significantly modified positions in this comparison.

**Comment by weir12** [comment]
But in a violin figure plotted by `plot Motif-centered Statistic Plotting` command,I have observed that P values centre on motif are Significantly less than surrounding base.(this is seem incompatible with the above text output of signif_sequence_context)
![image](https://user-images.githubusercontent.com/37523816/48458787-b5a70280-e802-11e8-81ab-4a866b77c865.png)

**Comment by marcus1487** [comment]
This plot and the most significant fasta output seem compatible to me. Note that on both outputs the statistic is the ‘-log(p-value)’. The most significant value of 1.3 from the most significant fasta is likely not included since it does not occur near the motif of interest specified in the plotting command. Hopefully this clears up these results.

**Comment by weir12** [comment]
Thanks,you made it clear.
One more question:has the p-values been adjusted by fisher's method?Are the extracted  significant regions based on the rank of adjusted p-values?

**Comment by marcus1487** [comment]
P-values are computed using fishers method to combine p-values from a sliding window of bases. There is no multiple testing correction (or adjustment) applied to these values (if that was part of the question). The p-values in this plot are selected using the rank list over the whole genome, but filtered to only include regions with the motif specified (note the significant p-value selected from the rank list need not come from within the motif itself, but anywhere within the window shown in order to investigate significance of and within a motif of interest).
