### ISSUE TITLE
Inconsistency results for tombo

### ISSUE THREAD

**Issue by tengfeixiaozhu** [nanoporetech/tombo#135]
I run "annotate_raw_with_fastqs resquiggle detect_modifications" command in turn to get 5mC results in merged fast5 directory and seperated directory.  Then I merged seperated directory the output file, however I found the inconsistency result (The summed valid_coverage in seperated directory) with the result from merged fast5.  Here, I set the consistent parameter for all command (containing  --coverage-dampen-counts 0 0 ). 

I want to know if some random processing was done and whether fatal effect appear in the seperated directory.

**Comment by marcus1487** [comment]
There is no random processing in the `annotate_raw_with_fastqs`, `resquiggle` or `detect_modifications` commands. Additionally there is no interaction amongst the reads until the aggregation steps at the very end of the `detect_modification` step.

One possibility is that the fastqs were not pointed correctly between the batches of fast5s. In order to test this, run the `annotate_raw_with_fastqs` step with all fastqs in both sets of directories.

Another possibility if these commands were run simultaneously on the same set of reads (one pointed to the sub-directories and one to the parent directory) is that events were in the process of being overwritten while the other command was being processed. `tombo resquiggle` currently writes data to the FAST5 files, so this could be disrupting this particular test. If this test could be completed on two copies of the same reads, that would test for this case.

**Comment by marcus1487** [comment]
Has this issue been resolved?
