### ISSUE TITLE
Why does the Tombo “Text Outputs” commmand produce  negative chain results in RNA direct sequences 5mC analysis

### ISSUE THREAD

**Issue by wlhCNU** [nanoporetech/tombo#140]
Hi marcus:
Why "tombo text_output browser_files --file-type  dampened_fraction" commmand produce negative chain results(tombo_results.dampened_fraction_modified_reads.minus.wig)? 

Because the direct RNA is the native RNA product, should these direct RNA be directly aligned with the reference transcriptome sequence when aligned, without the need for second reverse alignment?

How should the results of these negative chains results be explained? 

Thanks

**Comment by marcus1487** [comment]
The reverse strand results are not specifically excluded as some samples can have transcription from both strands (e.g. bacterial samples mapped to the genome). Specifically excluding these mappings could technically be accomplished, but I think the settings where this is needed are few (since the minus.wig result files can just be ignored if not needed). 

As for explanations for the reverse strand mappings, this is more of a sample specific biological question. There are many biologically significant reasons these mappings could be produced, as well as certainly many reasons that these could arise from artifacts largely dependent on sample prep. 

If these mappings are not meaningful for your application, they could certainly be ignored, but knowing this has to do with the biological sample of interest.
