### ISSUE TITLE
Tombo Restart Error

### ISSUE THREAD

**Issue by nhartwic** [nanoporetech/tombo#156]
I am attempting to use tombo to do methylation detection and am encountering an error that can't be clearly resolved. I initially started the  resquiggle step with 8 processes but upon seeing progress, I killed the run in order to restart with 32 processes. I am now unable to run tombo resquiggle  on these reads. Any attempt to do so is greeted with the following error.

[16:32:18] Loading minimap2 reference.
[16:33:58] Getting file list.
******************** ERROR ********************
        Unexpected error during file enumeration. Check that you have write permission within the specified [fast5_basedir].

I've verified that I do have permissions to read/write the files. Any assistance with debugging this would be appreciated.

**Comment by marcus1487** [comment]
This may be related to the hidden read lock files tombo places on directories currently being processed. Try setting the `--ignore-read-locks` flag.

**Comment by nhartwic** [comment]
I'm already running with the --ignore-read-locks flag. If I attempt to run without it, I get the following errors.

[16:50:06] Loading minimap2 reference.
[16:51:39] Getting file list.
******************** ERROR ********************
        This set of reads is currently being processed by another resquiggle command. Multiple resquiggle commands cannot be run concurrently on a set of reads to avoid corrupting read files. If you are sure this set of reads is not being processed by another command (usually caused by previous unexpected exit) set the --ignore-read-locks flag.
******************** ERROR ********************
        Unexpected error during file enumeration. Check that you have write permission within the specified [fast5_basedir].

**Comment by marcus1487** [comment]
If you could clone from github, add a `raise` at [this line](https://github.com/nanoporetech/tombo/blob/273fad8bdbdf10fee4bf049720767561848f1497/tombo/tombo_helper.py#L1048) and install `pip install .` (from tombo base directory) and re-run your command that would give me a lot more information about why this error is occurring.

**Comment by nhartwic** [comment]
either I'm not encountering that raise in subsequent tests or its being caught somewhere else. Here is the new error...

[17:30:10] Loading minimap2 reference.
[17:31:48] Getting file list.
******************** ERROR ********************
        Reads base directory or a sub-directory does not appear to be accessible. Check directory permissions.

**Comment by marcus1487** [comment]
Most likely the latter. Caught one level up. Try a raise [here](https://github.com/nanoporetech/tombo/blob/273fad8bdbdf10fee4bf049720767561848f1497/tombo/resquiggle.py#L1956) now.

**Comment by nhartwic** [comment]
Ok, Here is the actual error

PermissionError: [Errno 13] Permission denied: {SNIPPED}/.reads.tombo.lock'

While I have RW priveldges for all the read files, I apparently don't have permissions for the lock files that tombo creates. I missed this during my checks earlier because the lock files are hidden files. The weird permissions here are probably a result of some combination of the way I'm running tombo (using a qsub command to execute it on a cluster) along with the fact that I don't usually have write permissions for the folder in which the fast5s are stored.

I suppose I'll need to contact my server manager to get them to give me write permissions for those lock files as well.

In general, this seems like a software architecture problem. As far as I can understand it, these locks are only really needed because tombo is overwriting its input. This is undesirable for a  number of reasons the least of which is this specific permissions problem I've encountered. I/O really should be separated.

**Comment by marcus1487** [comment]
I'm glad we were able to get to the root of this issue. Given the current tombo workflow and architecture it seems that this would be the desired result from tombo (albeit a better error message would help here).

As you note, a change to the software architecture would certainly be the correct fix in the long term for this project, but it seems there is a confusion here. The lock is necessary to keep more than one tombo process from accessing a set of reads simultaneously, not due to overwriting the input. Tombo does not overwrite the input files, but adds a new group in the HDF5 data files and adds data to that new group. The `--overwrite` flag will only overwrite data in this tombo-specific slot within the `Analysis` slot from the FAST5.

This software architecture decision was made as it has the advantage of including all (and little more) of the necessary information to detect modifications in downstream steps and does not copy large signal data to a new intermediate file format. Modifying the input files also has downsides as well (such as the lock file permissions issue experienced here). Converting to a new tombo intermediate file format would be the way forward, but is a large amount of effort and is thus not in the short term development plans. The larger issue of adding information back into the FAST5 file is certainly being taken into account in future software developments (across software packages).
