### ISSUE TITLE
annotate_raw_with_fastqs crash if fastq filename is a directory

### ISSUE THREAD

**Issue by lappazos** [nanoporetech/tombo#161]
i ran the it with dir instead of filename, waited 3 hours for the preparation process and then it crashed only when reaching the second part - the error should be checked in the code at the begging to prevent time loss.

if i have multiple fastq files i should just put their names one by one at the same command?
what happens if i run again without overwriting?
if the reads preparation was already done and it crashed while trying to annotate, is there a way to skip the preparation process from running again?

Thanks!!! 

![Screenshot from 2019-03-28 20-01-20](https://user-images.githubusercontent.com/44434045/55181536-859a4380-5194-11e9-8745-10e9b83d6346.png)

**Comment by marcus1487** [comment]
It would certainly help to check the FASTQs at the beginning, but since there can be many FASTQs, so this operation would likely only check the very beginning of the first FASTQ provided. This will be noted as a TODO for this command.

This first step can also be drastically sped up by passing in the sequencing summary file to avoid time lost due to errors later in processing.

For passing multiple FASTQ files, unix performs filename expansion, so you can replace all of these filenames with `--fastq-filnames fastq_dir/*.fastq` instead of listing all of the files.

For running again without setting `--overwrite`, (as noted in the warning message in the second command) this will not add base calls to the reads since the slot for the basecalls was created in this first run and must be overwritten in this second command.

There is unfortunately not a way to skip the FAST5 read_id indexing step (slow first step), but as noted above if sequencing summary file(s) can be provided this will drastically speed up this first step.
