### ISSUE TITLE
Mapping Tombo VS minimap

### ISSUE THREAD

**Issue by marctormo** [nanoporetech/tombo#164]
Hello!

I have mapped some reads (fastq) against a reference using minimap and I've also resquiggled those reads (fast5) with tombo. With minimap I'm obtaining 80% reads mapped and with tombo around 60%:
[17:37:37] Final unsuccessful reads summary (39.7% reads unsuccessfully processed; 731849 total reads):
    31.7% ( 584774 reads) : Alignment not produced                                                          
     5.2% (  95761 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`) 
     2.8% (  51292 reads) : Read event to sequence alignment extends beyond bandwidth                       
     0.0% (      9 reads) : Base calls not found in FAST5 (see `tombo preprocess`)                          
     0.0% (      8 reads) : Not enough raw signal around potential genomic deletion(s)                      
     0.0% (      4 reads) : Too much raw signal for mapped sequence                                         
     0.0% (      1 reads) : Unexpected error

I am trying to understand if this is a normal behaviour, and where could be the difference of 20% mapped reads.
Could you please clarify my doubts?

Many thanks!
Marc

**Comment by marcus1487** [comment]
The alignments should be the same with a couple of minor points. One that may be influencing this result is multi-mapping reads. In tombo the aligner is set to return only the best alignment. Thus if multimappers are included in the mapped percentage this may be the issue here. 

Another common issue here are the minimap2 and mappy versions (`python -c "import mappy; print(mappy.__version__)"` and `minimap2 --version`). 

The last point to check is that the exact same base calls are being used. This can be confirmed by using the `tombo preprocess annotate_raw_with_fastqs` command.

Hopefully this can identify the issue here.

**Comment by marctormo** [comment]
Thank you for your suggestions, but it seems the problem is still unclear. 
About the multimappers, when I see the flag (from samtools) I don't find them. I did it with all fastq, and only with "pass" with the same percentage
2289839 + 0 in total (QC-passed reads + QC-failed reads)
68 + 0 secondary
447125 + 0 supplementary
0 + 0 duplicates
1705065 + 0 mapped (74.46% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

I also checked both versions, and I'm working with the same: 2.11

And now it's finishing the resquiggle after running the preprocess annotate_raw_with_fastqs, obtaining the same results (63% completed):
5 most common unsuccessful read types (approx. %):50  365-00:00:00 2019-04-04T16:11    R     1     8 2019-04-04T15:20:01 mr-00-25        
    31.6% ( 364281 reads) : Alignment not produced                                                          
     5.2% (  59905 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`) 
     2.8% (  32420 reads) : Read event to sequence alignment extends beyond bandwidth                       
     0.0% (      6 reads) : Not enough raw signal around potential genomic deletion(s)                      
     0.0% (      3 reads) : Too much raw signal for mapped sequence                                         
 63%|██████▎   | 1154100/1842655 [17:00:14<10:08:41, 18.85it/s][mtormo@mr-login 20190321_FLO-MIN106_SQK-LSK109-K2_c-acnes-2]$ 

Do you know if there's a problem with basecalling with guppy? It's the first time I used guppy.
I executed the basecalling with 2 different runs with these arguments:
--flowcell FLO-MIN106 --kit SQK-LSK109 -t 8 --qscore_filtering  --min_qscore 7 -r --fast5_out --records_per_fastq 0 
I created symlinks for all the fast5 in both runs in one path, where I ran multi_to_single_fast5. After, I ran tombo resquiggle (or tombo preprocess annotate_raw_with_fastqs + tombo resquiggle).

Do you have any idea?
Thank you very much,
Marc

**Comment by marcus1487** [comment]
This should not be an issue with guppy as the input basecalls are the same for both tombo and minimap2.

I believe that this is an issue with how minimap2 reports secondary alignments. Minimap2 can produce multiple primary alignments for a single read when there is a split alignment or a equally likely alignments. And samtools flagstat is reporting the percentage of mapped *alignments* not *reads*. This is shown since tombo lists a total of `1842655` reads for this run while samtools flagstat reports `2289839`. To confirm could you count the number of record in the input fastq?

**Comment by marctormo** [comment]
Thank you Marcus,
The number of reads of the fastq file is 1842646 (1568828 pass), as you said, I can't compare those numbers. Now it's just curiosity but, how do I get the same alignments for both? Which are the parameters to apply to minimap, then?

Best regards,
Marc

**Comment by marcus1487** [comment]
I think this should be a filtering of the minimap2 alignments to only use the highest scoring alignment for each read, but I am not certain of this behavior. I am also not certain how minimap2 determines which alignment to report when multiple alignments have the exact same score.

**Comment by marctormo** [comment]
Thanks for your help
