### ISSUE TITLE
resquiggle multiple subfolders

### ISSUE THREAD

**Issue by Huanle** [nanoporetech/tombo#168]
Hi There,

Will resquiggle on multiple subfolders give different results from resquiggling on one folder containing all fast5 files?
I noticed that each resquiggling will generate a genome index file. So, is there a way to combine them into a single one?
 
Thanks.

**Comment by marcus1487** [comment]
There is not difference between running re-squiggle on multiple subfolders or one call to the parent folder. There is no way to explicitly combine these tombo index files, but when calling any tombo command all of the subfolders can be passed together and will be processed as if they were merged.

**Comment by Huanle** [comment]
Thanks @marcus1487 for your answer. 
I asked this because i have a large dataset. If possible to process subfolders separately and then combine the tombo index files, it will be more efficient to run resquiggling parallelly.   
Anyway, thanks.

**Comment by marcus1487** [comment]
To be clear, the tombo index files would not be combined, but using any tombo command downstream of the `resquiggle` command can take multiple directories which have been `resquiggle`d. Thus there is no effective reason to merge the tombo index files and you should be able to perform separate subdirectory `resqiuggle` processing (though the `resquiggle` command can efficiently take advantage of multiple cores on the same machine for larger data sets).

**Comment by Huanle** [comment]
@marcus1487 thanks again for your explanation. I did not mention that these sub-directories containing fast5 files belong to the same sample. My understanding is that I will have to run tomobo **resquiggle** with the parent directory (consisting of all subdirectories) as the **fast5_basedir**. I also have been thinking the genome index file will be needed for downstream analyses as well.  But in fact, it is not necessary for the downstream analyses? right?

**Comment by marcus1487** [comment]
The `fast5_basedir` can be any directory containing fast5 read files. If given the parent directory tombo will recursively search for fast5 files in each subdirectory. If given a subdirectory only the files within that subdirectory would be processed.

I'm not sure I understand exactly what is meant by a genome index file. The resquiggle command requires a reference file. This can be a minimap2 index file or a reference fasta file. This file is not required for downstream analyses as the portion of the reference mapped to each read is stored back into the fast5 (in the tombo analysis group). The same genome index can also be passed to multiple resquiggle commands simultaneously as it is only read. But the same read directory should not be simultaneously processed with multiple resquiggle commands due to HDF5 IO issues, but tombo will not allow this behavior without setting a flag to allow this.

This all being said, tombo should be able to efficiently make use of multiple cores to process from the parent directory, so processing each subdirectory individually should not be necessary. In fact processing each subdirectory individually will use far more RAM and compute as the genome would have to be loaded for each individual process, where running the entire sample together loads the genome reference only once in a shared memory space.

**Comment by Huanle** [comment]
Thanks again @marcus1487 .
The index file i mentioned is the hidden file such as **\*RawGenomeCorrected_000.tombo.index** produced by **resquiggle**.  I tried running resquiggle on subdirectories one by one, it generated one index file for each subdirectory. So I think maybe only one index file for all fast5 files belong to one sample is required. Therefore, it might require  combination of those index files produced for each single subdirectory. 
But if the index file won't be used for the downstream analyses, then i have been overthinking it.

**Comment by marcus1487** [comment]
I have been referring to this file as the tombo index file. This file is certainly read by the downstream analyses, but there is no command to merge these files as they are actually linked to the structure of the reads stored within the processed directory.

But there is no real reason to merge the files. All tombo commands after `resquiggle` can take multiple fast5_dirs and the tombo indices will effectively be merged in memory each time (with little overhead versus reading from a single merged index). Thus there is no need to merge the tombo index files.

**Comment by Huanle** [comment]
Thanks @marcus1487  for clarifying this.
