### ISSUE TITLE
Command line wrapper API to output table of per-read statistics?

### ISSUE THREAD

**Issue by Shians** [nanoporetech/tombo#174]
I would like to get per-read methylation statistics much like the output of nanopolish, where each row should contain at least `chr`, `pos`, `read_name`, `methyl_likelihood` or something equivalent. This is currently possible through the Python API, but this is lacking in error reporting and documentation.

There are no errors if an unrecorded chromosome is queried, making it difficult to know if a query was valid. It's unclear if it's possible to query what chromosomes are recorded, making it impossible to work with the per_read stat files without querying either the reference genome or the aligned BAM. Leaving the strands argument as None in `intervalData` always returns no reads, where I was hoping it would return reads from either strands.

It would be very nice if tombo could provide a command-line API under text-output to produce a tabular form of the per-read modification statistics.

**Comment by marcus1487** [comment]
I have just added a script (`scripts/dump_per_read_statistics.py`) to the repository in order to dump a per-read statistics file to a text file. Note that this output also includes strand as tombo computes statistics on each strand independently for most all operations.

For the error processing, you can check the valid chromosome strand values with the (undocumented) `blocks_index` attribute of a `PerReadStats` object (as used in the script). Though this will not include any chromosome and strand combinations that don't have mapped reads, so checking the reference file or BAM is still the best option for a list of all valid chromosomes.

For the strand option, the choice to not return both strands of information is intentional as this would be quite confusing, as no information concerning the strand for each record is recorded in the return information. Most per-read statistics should be treated independently across both strands and only combined in specific situations, e.g. CpG methylation on both strands. In order to extract information from both strands consecutive calls with `+` and `-` could be made and thus maintaining the strand information.

**Comment by Shians** [comment]
Thanks for the quick response Marcus, it works great!
