### ISSUE TITLE
Q on tombo filter level_coverage with multiple index files

### ISSUE THREAD

**Issue by OlivierZablo** [nanoporetech/tombo#187]
Hi Marcus,

I'm looking at RNA samples, and doing the model sample compare where I do modif. detection with a set of IVT fast5s and a 'natural' sample. I'd like to even the IVT read coverage along my reference genome because the PCR'ed IVT controls have coverage spikes. So thankfully, you thought of everything and I found the tombo filter level_coverage! My Qs are:

1) I currently use three separate IVT directories when doing modif. detection, each with their own hidden index files. So should I run 'tombo filter level_coverage' on all 3 directories at once with the same '--percent-to-filter' value. And if I do that, will it take the set % of all three directories _combined_ or the set fraction will be applied separatly in their own directory? I'm guessing each index file is filtered independently...

2) could you provide more guidance on what the command does? I've read your tutorial, and I think I got it, I'm just not sure what % I should use to achieve even coverage for my genome...

Thanks in advance!

**Comment by marcus1487** [comment]
1) The fraction is applied to each index separately. See [here in the code](https://github.com/nanoporetech/tombo/blob/1.5/tombo/_filter_reads.py#L305) for this implementation. It would be possible to split the filtering over the directories, but would be bit more complicated internally due to the separate indices (as you have guessed).

2) This method computes the global mapping coverage. Then assigned each read the coverage at the central point for that read. That value is used as the weight for selecting the read for filtering. Then a set of reads to filter is randomly chosen with this weighting (see [here in the code](https://github.com/nanoporetech/tombo/blob/1.5/tombo/_filter_reads.py#L141)). 

In practice I generally filter a small fraction (20%; but maybe more depending on level of coverage spikes), run `tombo text_output broswer_files --file-types coverage` and load into IGV to see if I've removed enough. Then I iterate until the coverage is "even enough". I have a [TODO note](https://github.com/nanoporetech/tombo/blob/1.5/tombo/_filter_reads.py#L109) to perform iterative rounds of this filter when the percentage is high >50% as this will completely deplete the high coverage locations for very high fractions requested (since the weights are computed just once).

**Comment by OlivierZablo** [comment]
Thanks a lot Marcus, much appreciated for your fast reply. I will try iteratively then and see when it sort of evens out throughout.
