### ISSUE TITLE
6mA detection in human

### ISSUE THREAD

**Issue by benhur974** [nanoporetech/tombo#203]
Hi, we are planning to sequence human gDNA on PromethION. We are wondering if we would be able to detect 6mA DNA methylation using Tombo (motif specific or not). If yes, what would be the expected accuracy? Thanks.
Ben

**Comment by marcus1487** [comment]
Tombo comes with an "all-contexts" 6mA model, though the performance of this model is not close to the performance of a motif-specific model. The motif-specific model (trained for dam methylation) performs very well. If a motif-specific model could be trained this would be the ideal given the current software available.

We are also working towards more accurate modified base models to be processed with the [megalodon software](https://github.com/nanoporetech/megalodon), so that may be a more attractive option in the near future. Modified base models for use with megalodon can also be trained by the community using the [taiyaki package](https://github.com/nanoporetech/taiyaki).

**Comment by benhur974** [comment]
Hi Marcus, thanks for your reply! Does megalodon be limited to dam methylation or an all-contexts or additional motif specific models will also be available?

**Comment by marcus1487** [comment]
For 6mA megalodon is currently limited to dam methylation in the training data set. For 5mC megalodon can currently detect CpG and dcm methylation. We are currently working to provide models to detect modifications in more contexts.

**Comment by benhur974** [comment]
Thanks for the comments !
