### ISSUE TITLE
resquiggle in parallel

### ISSUE THREAD

**Issue by lucacozzuto** [nanoporetech/tombo#210]
Dear developer,
I'm running resquiggle in parallel on different subfolders and I would like to use them for detect_modifications but it fails since it is not able to read the different indexes... I'm wondering if there is a way to join the tombo indexes...

Thanks,
 
Luca

**Comment by marcus1487** [comment]
It should not be necessary to join the tombo indices. The `detect_modifications` command can read and join multiple indices on the fly, but needs to be pointed to the exact same directories as were pointed to by the `resquiggle` commands. Passing the parent directory (from the `resquiggle`'d subfolders) will not allow `detect_modifications` to access the index files. Instead pass all of the subfolders individually to the `detect_modifications` command.

As a side note, it should not be necessary to run the `resquiggle` command in separate processes and in fact should be more efficient to run all subfolders with a single `resquiggle` command. The efficiency gain is due to the reference sequence only needing to be loaded a single time when run as a single job. 

Hopefully this help in your tombo processing, but let me know if you have further issues.

**Comment by lucacozzuto** [comment]
thanks a lot!
Btw having hundreds of files and a big cluster I was thinking to parallelize as much I can. Can you please explain me how to pass the 200 subfolders to the command line, please?
Thanks again!

**Comment by marcus1487** [comment]
If the 200 directories match a pattern or are all in the same location unix wildcards can be used. For example one could run: `tombo detect_modifications de_novo --fast5-basedirs parent_fast5s_dir/*` where each subdirectory under `parent_fast5s_dir` was processed with `resquiggle`.

In terms of making use of a large cluster, passing a larger `--processes` value (and specifying this value via the job queuing system) should be more efficient than running the same number of processes each processing a single subdirectory. If looking to take advantage of more processes than a single node contains, then spreading the subdirectories over many jobs may be more time efficient.

**Comment by lucacozzuto** [comment]
thanks! I'll try and let you know.

**Comment by lucacozzuto** [comment]
It worked! Many thanks!
