### ISSUE TITLE
errror when running 'test_significance'

### ISSUE THREAD

**Issue by Huanle** [nanoporetech/tombo#22]
command:
$  tombo test_significance --control-fast5-basedirs unmodified_curlcake/fast5 --fast5-basedirs m6A_25pcnt/ --statistics-file-basename m6A_25pcnt_VS_control --processes 10 

error message:
Parsing tombo index file(s).
WARNING: Index file does not exist for one or more directories. For optimal performance, either re-run re-squiggle without --skip-index flag or point to top level fast5 directory of recursive directories.
Performing two-sample comparison significance testing.
Parsing tombo index file(s).
Performing significance testing across 1 regions. (Will print a dot for each batch completed)
.
********** ERROR *********
        No genomic positions contain --minimum-test-reads.

First, the index files were indeed produced by the previouse resquiggle analysis.
So, i do not understand why the warning msg was generated. 

-rw-r--r-- 1 hualiu g_neuro_mattick 14722 Feb  1 19:22 unmodified_curlcake/.fast5.RawGenomeCorrected_000.tombo.index

-rw-r--r-- 1 hualiu g_neuro_mattick 747 Feb  1 13:50 m6A_25pcnt/.fast5.RawGenomeCorrected_000.tombo.index

Second, I do not know what causes the error message:
       " No genomic positions contain --minimum-test-reads."

It would be nice if you can help me figure out what's going on.
Thanks a lot.

Huanle

**Comment by marcus1487** [comment]
Hi Huanle,

The warning message is because the terminal path for the `--fast5-basedirs` on which you ran the `resquiggle` command and the one used in the `test_significance` command are different. From the hidden file you presented it appears as though you have left the `fast5` off of the end of the path for the `--fast5-basedirs` value. The valid reads should still have been found since they are nested below this directory (the reading can just be slower since all FAST5 files have to be queried again). I will add a hint to this warning message as well as a note in the docs for this point in the next release.

The final error message is due to a threshold set in the `test_significance` command so that very low coverage regions are not stored in the stats file. This option defaults to 5, so locations with fewer than 5X coverage in both samples will not be tested. You can check the valid (`tombo resquigggle` processed) coverage with the `write_wiggles` command. You could also set this value to `1` so that all regions are tested, but the fraction of significant locations will obviously be much less meaningful. I have included a potential fix to this low coverage fraction significant issue in the next release (coming soon).

If it does appear as though you have valid coverage regions please let me know.

**Comment by Huanle** [comment]
Thanks heaps for your help.
It seems to be working when i lower the minimum-test-reads to 1 .
**$ tombo test_significance --control-fast5-basedirs unmodified_curlcake/fast5 --fast5-basedirs m6A_25pcnt/ --statistics-file-basename m6A_25pcnt_VS_control --processes 10 --minimum-test-reads 1**
Parsing tombo index file(s).
WARNING: Index file does not exist for one or more directories. For optimal performance, either re-run re-squiggle without --skip-index flag or point to top level fast5 directory of recursive directories.
Performing two-sample comparison significance testing.
Parsing tombo index file(s).
Performing significance testing across 1 regions. (Will print a dot for each batch completed)

However, when i ran 
$ **tombo write_wiggles --fast5-basedirs m6A_25pcnt/fast5 --wiggle-basename m6A_25pcnt --statistics-filename m6A_25pcnt.write_wiggle.stats --wiggle-types fraction coverage**        

Loading statistics from file.
************************************************************
ERROR: No statistics file provided.
************************************************************

Does this imply the data quality is too bad for the analysis to proceed ?

Thanks.

Huanle

**Comment by marcus1487** [comment]
I believe you have the statistics filename incorrect in the `write_wiggles` command. According to your `test_significance` command the output filename should be `m6A_25pcnt_VS_control.tombo.stats`. The test_significance command takes a basename only since once multiple alternative models are available they can be run together and they will be output accordingly. 

I hope this helps and best of luck!

**Comment by Huanle** [comment]
Hi Marcus,

Indeed, you are right.

Thanks heaps for your help.
