### ISSUE TITLE
unexpected high amount of reads with "Reference mapping contains non-canonical bases" in re-squiggle process

### ISSUE THREAD

**Issue by lixuwen1997** [nanoporetech/tombo#221]
Hi Marcus,

When I tried tombo resquiggle to mtDNA reference. I got 70% of my reads are unsuccessful because of  "Reference mapping contains non-canonical bases". Below is the detail output. Could you help me with this problem? Is this a issue with my reference fasta file? But I just downloaded it from ncbi (https://www.ncbi.nlm.nih.gov/nuccore/251831106), and it works fine when I use it with minimap2. Thanks a lot.

```
tombo resquiggle --dna my_single_fast5_dir/ human_chrM.fasta --processes 50 --overwrite --num-most-common-errors 5
[13:46:54] Loading minimap2 reference.
[13:46:54] Getting file list.
[13:46:54] Re-squiggling reads (raw signal to genomic sequence alignment).
5 most common unsuccessful read types (approx. %):
    69.7% (    299 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
     9.6% (     41 reads) : Read event to sequence alignment extends beyond bandwidth
     7.2% (     31 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`)
     0.2% (      1 reads) : Alignment not produced
     -----
100%|##########| 431/431 [00:48<00:00,  8.82it/s]
[13:47:43] Final unsuccessful reads summary (86.8% reads unsuccessfully processed; 374 total reads):
    69.4% (    299 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
     9.7% (     42 reads) : Read event to sequence alignment extends beyond bandwidth
     7.4% (     32 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`)
     0.2% (      1 reads) : Alignment not produced
[13:47:43] Saving Tombo reads index to file.
```

**Comment by marcus1487** [comment]
This is indeed an issue with the reference file. This error occurs downstream of minimap mapping and actually indicates that mapping proceeded successfully for all of these reads. The issue is that the mapping is over a non-standard base (non-`ACGT`). When this happens tombo can no longer map the signal to the reference as there would be a stretch of unknown bases/levels. 

There are a couple of avenues one could take to workaround this issue, but it depends on the details of the issue and final goals. One possibility would be to infer the identity of these bases and replace them in the reference. If this is not possible one could split the reference at any non-standard bases, into sort of fully-known reference "contigs". This will likely effect mappings though as you are observing many reads mapping over these non-standard bases. There may well be additional workarounds. 

Hopefully one of these fixes can address your case here, but please do post if not.

**Comment by lixuwen1997** [comment]
Thank you so much. I found a N in the reference. And the _"Reference mapping contains non-canonical bases"_ error is gone after I corrected it. But I still got  reads with  _"Read event to sequence alignment extends beyond bandwidth"_ and _"Poor raw to expected signal matching"._ 
`[14:43:54] Final unsuccessful reads summary (45.7% reads unsuccessfully processed; 197 total reads):
    27.6% (    119 reads) : Read event to sequence alignment extends beyond bandwidth
    17.9% (     77 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`)
     0.2% (      1 reads) : Alignment not produced`
Could you explain a bit about the reasons to generate these two types of errors and how can I avoid them? Thanks a lot.

**Comment by marcus1487** [comment]
Details for failed reads can be found [here in the docs](https://nanoporetech.github.io/tombo/resquiggle.html#common-failed-read-descriptions). The `Read event to sequence alignment extends beyond bandwidth` is closely related to the `Not enough raw signal around potential genomic deletion(s)` error described there. You can also see the algorithm details above which show the adaptive bandwidth step. When the traceback path comes too close to the edge of the bandwidth these reads are filtered with this failed read message. In short this means that the signal to reference mapping is poor and likely incorrect. This can happen for a large number of reasons (e.g. very high mod content, incorrect reference, etc.).

**Comment by lixuwen1997** [comment]
I see. Thank you so much.
