### ISSUE TITLE
plot motif_with_stats visualization issue

### ISSUE THREAD

**Issue by etvedte** [nanoporetech/tombo#234]
I am using tombo plot motif_with_stats to confirm suspected methylated motifs in E. coli. The command I used is:
```
tombo plot motif_with_stats --fast5-basedirs fast5_dir --statistics-filename 6mA.tombo.stats --genome-fasta ecoli.genome.fasta --motif GATC --plot-standard-model --num-statistics 10000 --num-regions 1
```
In the bottom portion of the plot, some bases do not have the violin-plot displayed. Do you know why this happens? I've included a second pdf for the ATGCAT motif where the fifth residue (adenine) should be methylated, the squiggles for the raw signal on the top half of the plot suggests deviation from canonical base model, but there is no violin plot data.

Also, could you explain in more detail the --num-context parameter? What is the default value if it is not set explicitly in the command? My interpretation of this is that it limits the search space to X residues surrounding the motif of interest in the event a flanking region contains higher fractions of modified reads. Let me know if this is correct.

Thanks for the assistance and for the tool.
[LIG.6mA.alt.plot.GATC.pdf](https://github.com/nanoporetech/tombo/files/4405571/LIG.6mA.alt.plot.GATC.pdf)
[LIG.6mA.alt.plot.ATGCAT.pdf](https://github.com/nanoporetech/tombo/files/4405572/LIG.6mA.alt.plot.ATGCAT.pdf)

**Comment by marcus1487** [comment]
The blank slots in the lower facet of these plots are due to a lack of test statistics at these locations. My guess would be that these are results from an `tombo detect_modifications alternative_model` call. This method only makes calls at the specified canonical base (A for 6mA calling). Thus these locations are blank since an A will never occur at this position of the specified motif.

In general this plot is intended for de novo modified base detection results since the location of the modified base is unknown in this case. The shifts in signal at positions away from the detected A bases are indeed the purpose for the alternative models (signal shifts happen at several locations around to the modified base and the alternative models attempt to model this).

The `--num-context` parameter does two things. The simpler is setting the window width of these plots. The requested motif along with `--num-context` bases to either side are plotted. The second thing is that this is the width of sequence searched around the most significant modified base results. In more detail all modified base statistics are iterated in order from most significant to least significant. For each site, if the motif of interest is present within the `--num-context` bases the site is added to the data to be plotted; if not it is skipped. This continues until `--num-statistics` have been accumulated. The statistics at each site are arranged so that they are relative to the motif of interest. In this way if a real motif occurs in this motif then a peak should be apparent at (or near) the modified base. If no motif is consistently present at this motif then no peak should be present. In fact if there are true modified bases in a sample, but not at the specified motif the motif itself should show a valley of significance values within the motif since real modified bases will occur around the motif at some locations.

For the default value, this can be found for any parameter by adding the `-h` flag. The default for the `--num-context` parameter is `5`.
