### ISSUE TITLE
modified base detection - human CpG

### ISSUE THREAD

**Issue by clariB** [nanoporetech/tombo#236]
This is the command I ran for human CpG methylation detection:
tombo detect_modifications alternative_model --fast5-basedirs Desktop/methylation_data/130and131/single130_131_fast5/0  --statistics-file-basename human_cpg_testing --alternate-bases CpG --processes 2

This is the output so far:
[14:45:58] Parsing Tombo index file(s).
[14:45:58] Performing alternative model testing.
[14:45:58] Performing specific alternate base(s) testing.
[14:45:58] Calculating read coverage regions.
[14:45:58] Calculating read coverage.

The resquiggle step ran fine and I got no errors while running it but it has been "calculating read coverage" for nearly 24 hours. does this step usually take this long or might there be something wrong with the fast5s or the command itself?

**Comment by marcus1487** [comment]
This step can indeed be slower, but this seems extremely slow. One issue here could be disk speed. You could try moving the data to faster disk location (not over NSF) in order to speed up this calculation.

The other suggestion would be to filter down to a test region to get a better estimate on the time required and/or split up the processing into more managable chunks. See [this command](https://nanoporetech.github.io/tombo/filtering.html#tombo-filter-genome-locations) to do this. Keep in mind the note at the top of that page as well (make a copy of your tombo index before filtering to be safe/restore previous filter status).
