### ISSUE TITLE
What is the concept for bandwidth

### ISSUE THREAD

**Issue by samll-rookie** [nanoporetech/tombo#253]
1、how to increasing the bandwidth in the script ?
I find the parameter (--signal-align-parameters DNA : 4.2 4.2 300 1500 20.0 40 750 2500 250) ，I should modify the second(300) or the three(1500) number as what is right?
#tombo resquiggle --signal-align-parameters 4.2 4.2 300 1500 20.0 40 750 2500 250 fast5dir genome.fa -processes 40 --num-most-common-errors 5

2、What is the concept for bandwidth ? I can't understand it better.

3、A large proportion for resquiggle is "Poor raw to expected signal matching"; What is the concept for it ? I remove the filter ,but I don't know how much impact it will have

_Originally posted by @samll-rookie in https://github.com/nanoporetech/tombo/issues/242#issuecomment-633830858_

**Comment by marcus1487** [comment]
1) The forth parameter (DNA default 1500) would be best to increase in order to avoid bandwidth errors. When the first bandwidth value (DNA default 300) fails for any reason the second value is used. If this fails then the read fails processing (and the reason is reported). This was implemented as a trade-off between speed and performance. Thus increasing this value further will increase the performance, but the processing speed will slow and memory requirements will increase.

2) Here is the documentation for the re-squiggle algorithm including discussion of the bandwidth: https://nanoporetech.github.io/tombo/resquiggle.html#sequence-to-signal-assignment

3) This indicates that the fitted levels from the signal do not match the expected levels within a range determined from a control sample. There are a large number of reasons for this (which include many modified bases). The main reason to remove these reads is that a number of them may be completely spurious assignments; for example when the step to detect the beginning of the sequence to signal alignment fails. Ideally, I would recommend inspecting the distribution of scores and choosing a new threshold instead of allowing all reads through this filter. If you are comfortable with python programming the reads can be read in as seen in [the first example here](https://nanoporetech.github.io/tombo/tombo.html#python-api-examples) and the per-read scores are stored in the `sig_match_score` attribute as described [here](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_helper.readData).

Best of luck!
