### ISSUE TITLE
Tombo for ONT direct RNA reads

### ISSUE THREAD

**Issue by akk01** [nanoporetech/tombo#255]
How can I use  Tombo for ONT direct RNA reads. One way is to used transcriptome as reference. But, using this basically cause problem in downstream analysis. Can splice-aware mapping be performed in someways in Tombo.

**Comment by marcus1487** [comment]
There is a core issue with splice-aware mapping and Tombo processing. At a very high level Tombo is designed to identify modified bases when the canonical ground truth sequence is known. If the ground truth sequence is not correct for a sample, this should be addressed before investigating modified bases. 

At a deeper level, the main issue is that reference locations are assigned an expected signal level based on the reference sequence. For spliced mappings this means that the splice junctions from a reference location may be different. Thus the "ground truth" sequence context for multiple reads mapping to the same reference base would have different expected signal levels (due to different bases on the other end of the splice junction). Allowing such situations in Tombo would require a complete re-think about how Tombo would function and especially how these different reads should be treated.

The recommendation in this case would be to map your reads to the genome reference to infer the transcriptome (or potentially supplement a reference transcriptome). Then this transcriptome reference could be used for analysis with Tombo.

**Comment by akk01** [comment]
I didn't quite understand the last paragraph. Which reference should be used - reference genome or referece cDNA fasta sequence.

**Comment by marcus1487** [comment]
Tombo should always be provided with a transcriptome reference. 

The last paragraph is explaining the recommendation for the case when a user does not have a transcriptome reference or believes that there may be novel transcripts found in a sample. In this case the recommendation would be that transcriptome be inferred from the reads in the sample (there are a number of packages available for this purpose). Then this new transcriptome can be used as input to Tombo for modified base detection.

**Comment by LeilyR** [comment]
Hi Marcus,
Thanks for a great piece of advice! I have followed that and in fact my question is about how to deal with them afterwards, I am having a hard time using the wig files having transcripts as chromosome name for downstream analysis or opening them on igv. Do you have any suggestion on that too?  thanks!

**Comment by marcus1487** [comment]
There are several command line tools available for this process. Gffread is one example [here](http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread_dl).

I would suggest first converting the WIG file to a GFF or GTF file as these are more standard formats for storing spliced transcripts. The WIG format is not designed to store spliced transcript coordinates.

**Comment by LeilyR** [comment]
Thank you so much @marcus1487 !
