### ISSUE TITLE
motif_with_stats coordinates of significant regions 

### ISSUE THREAD

**Issue by LeilyR** [nanoporetech/tombo#258]
Hi,

Is there a way to see the position of regions which the given motif has been found on them? what I mean is that if I could see the chromosome and position for each of those 3 default regions which are plotted. Thanks a lot!

Best,
Leily

**Comment by marcus1487** [comment]
There is not a straightforward way to output these locations. These locations are selected from the most significant locations as determined by the appropriate statistics (`dampened_fraction` for per-read aggregated models and `statistic` for `level_compare` methods). These locations are then filtered such that the region around the most significant locations must contain the motif of interest. One could use the `tombo text_output signif_sequence_context` command to perform this same procedure (note that the selected locations are dependent upon the context bases plotted in order to apply the motif filter; so the significant stats need not contain the motif, but must fall within the context requested for the plot).

In order to extract the exact locations plotted one could add a print statement [here in the code](https://github.com/nanoporetech/tombo/blob/13a506da63f19d65913f07ec90534724e578f69d/tombo/_plot_commands.py#L2114) as well.

**Comment by LeilyR** [comment]
thank you so much, I will give it a try.
