### ISSUE TITLE
Tombo Signal Mapping Clarification

### ISSUE THREAD

**Issue by TimD1** [nanoporetech/tombo#261]
For ordinary FAST5 files, `len(Signal) == first_sample_template + duration_template`. However, for Tombo FAST5 files, `len(Signal) != read_start_rel_to_raw + sum(Events['length'])`. They are approximately equal, but not quite the same (usually off by a few hundred signals at most). I've looked into whether the soft-clipped bases could account for the difference, but that doesn't appear to be the case either. Assuming bases are clipped only at the start, `{x where sum(Moves[:x]) == clipped_bases_start} * block_stride` is not equal to this difference. If these signals aren't being clipped or skipped, what happens to them?

The other alignment parameters, in terms of bases, make complete sense: `sum(Moves) + num_deletions - num_insertions - (clipped_bases_start + clipped_bases_end) == len(Events)`.

Graphing the signals at `Signal[read_start_rel_to_raw+Events['start']` for each event appears to be correct, but the actual alignments aren't great, and I'm not sure if there's an error on my part. The image below is a signal plot of a section of reference followed by three reads (alternating Guppy mapping and Tombo mapping). It appears that Guppy is much more consistent. I've drawn red lines from corresponding signal points on the Tombo mappings, which are all different. Is this typical behavior (and maybe this happens to be a difficult-to-map region), or must I be making a mistake?
![tombo_questionable_mapping](https://user-images.githubusercontent.com/13918078/83771681-89570f00-a650-11ea-97b3-8202ccb64128.png)

**Comment by marcus1487** [comment]
For the first question, The signal mapping does not proceed to the end of the signal, but stops usually before the end of the signal. Thus `read_start_rel_to_raw + sum(Events['length'])` defines the end of the signal assigned to sequence. There is no need to store `read_end_rel_to_raw` since the above value determines this. This value should always be less than the length of the signal. Also note that this may not correspond to the mapping from guppy (more on that below).

There are two separate issues with the second part of your question 1) Guppy vs Tombo signal assignments and 2) Tombo read-to-read variation. I'm also a bit confused by the attached plot. 

Are these Guppy and Tombo mappings from the same reads? If so why are the signal traces different? Is the x-axis in signal point space or some other space? if so how were the signal traces anchored from read to read?

For the Guppy vs Tombo question, in what sense is Guppy more consistent? The size of the Guppy events is more consistent since the model/neural network has a stride (most current models are stride 5). This means that bases (or "stay in the current base") outputs are only emitted every 5 signal points. This results in the highest accuracy basecalls, but not necessarily the best signal assignment for read-to-read comparison of signals. This was one of the main goals that the Tombo package solves.

For the Tombo read-to-read variation and signal assignments, something looks off on these (assuming these are the ones without the guppy basecall traces). Tombo "events" are generally not nearly this consistently spaces. How do the Tombo raw signal plots look for these reads using the Tombo raw signal plotting commands? As for the offset of the assigned signal positions in Tombo this is completely normal. Reads pass through the pores and varying speeds both between reads and within a read through time. This is why the re-squiggle/signal assignment/DTW step is necessary.

I hope some of this helps, but let me know if there you have additional specific questions.

**Comment by TimD1** [comment]
Thanks for the clarification that the signal mapping doesn't necessarily proceed to the end of the signal, that answers my main question!

To clarify the figure, the Guppy/Tombo mappings are from the same reads (and you're correct that the Tombo ones are without the Guppy basecall traces). However, I forgot to mention that I had re-scaled the length of each Tombo event in the graph to be equal, in order to align them to the reference for easier comparison. The attached graph should be more clear.

After more debugging, it turns out there was a typo on my end which caused the alignment issue in my graphs. Now it's clear that Tombo's mappings are much better than Guppy's! Thanks for your help!
![tombo_vs_guppy_mapping](https://user-images.githubusercontent.com/13918078/83804617-6a6e7200-a67c-11ea-8585-7042dca23982.png)

**Comment by PanZiwei** [comment]
@TimD1 Hi Tim I am really interested in the plotting part, would you mind telling me how you do the plotting? Any package for reference? Thanks!

**Comment by TimD1** [comment]
Unfortunately it's not from a single package which is easy to use. I wrote a script which used `pysam`, `h5py`, and `pyplot` to manually parse a FAST5 file, since I needed to work with the raw data for other reasons, and this graphing was a great way to verify I was using the data correctly.

I've attached the script below (now a different version), but it still has all the fundamental FAST5 parsing stuff which you should be able to borrow as needed, if you want to go through that effort.

[graph_signals.txt](https://github.com/nanoporetech/tombo/files/5071160/graph_signals.txt)

**Comment by PanZiwei** [comment]
> Unfortunately it's not from a single package which is easy to use. I wrote a script which used `pysam`, `h5py`, and `pyplot` to manually parse a FAST5 file, since I needed to work with the raw data for other reasons, and this graphing was a great way to verify I was using the data correctly.
> 
> I've attached the script below (now a different version), but it still has all the fundamental FAST5 parsing stuff which you should be able to borrow as needed, if you want to go through that effort.
> 
> [graph_signals.txt](https://github.com/nanoporetech/tombo/files/5071160/graph_signals.txt)

Hi Tim, it is really nice of you to share the script! Thank you so much!

**Comment by PanZiwei** [comment]
Hi @TimD1 ,
I am trying to go through your script but it seems that the script is applicable to SAM files. How do you get the SAM files? Did you use Minimap2 for alignment to convert .fq into .sam files? What if I only have the file in .fast5 format after Tombo re-squiggle?

Thank you so much for your help!
