### ISSUE TITLE
Missing genome positions from text_output

### ISSUE THREAD

**Issue by tueknielsen** [nanoporetech/tombo#265]
First of all, thanks for tombo!

When writing browser files with fraction of modified reads, the output bed files do not have lines for every single position in the reference genome. Most notably, the first few bases in the start and the end of the genome are not included, but also "random" positions throughout the genome. I assume that this is due to bad/missing alignments of reads?
Is there any way to enable or force writing values (fraction) for all genome positions? I can live with writing a "0" value to these few missing positions.

Best regards,
Tue

**Comment by marcus1487** [comment]
This functionality does not currently exist within Tombo. The gaps at the edge of contigs/chromosomes likely come from the inability to assign signal to these locations (since a valid k-mer with context on both sides cannot be retrieved).

Unfortunately this feature is not likely to be added as Tombo is  in a "bug fix only" support state. We are making efforts to replace most all Tombo functionality. Much of this functionality has been addressed in Megalodon at this point.

If this is required for downstream processing, I would suggest a custom script.

**Comment by tueknielsen** [comment]
Thanks for your reply. I did solve it with a custom script. 
I will have to take a look at Megalodon soon, but I have been quite happy with Tombo and its features.
