### ISSUE TITLE
Should the sequence of Direct RNA Sequencing be reveresed before resquiggle?

### ISSUE THREAD

**Issue by PengNi** [nanoporetech/tombo#269]
Hi,

I am a little confused after reading [https://nanoporetech.github.io/tombo/rna.html](https://nanoporetech.github.io/tombo/rna.html).

Since RNA is sequenced in the 3' to 5’ direction, should the basecalled sequence be reversed before **re-squiggle**? I also noticed that Guppy has `--reverse_sequence` option for RNA sequenceing, should I use this option for basecalling before the re-squiggle process?

Thanks in advance!

Best,
Peng

**Comment by PengNi** [comment]
I noticed that `--reverse_sequence` in Guppy is set as `true` by default. Should I use the default `true` or set it as `false`?

Best,
Peng

**Comment by marcus1487** [comment]
The default of `true` for `--reverse_sequence` should be left for direct RNA reads. The basecalls always should be in "reference orientation". Since direct RNA is sequenced from 3' to 5' this means reversing the sequence relative to the signal. When running Tombo the `--rna` can be added to ensure that Tombo correctly processes the direct RNA signal, though Tombo should be able to detect this automatically.
