### ISSUE TITLE
Question about tombo.DNA.model

### ISSUE THREAD

**Issue by BoredMa** [nanoporetech/tombo#278]
Hi, I want to know why all standard deviations are the same value in tombo_models/tombo.DNA.model? std=0.35287...?
![image](https://user-images.githubusercontent.com/25764447/90230379-091d0900-de4c-11ea-83b0-12a098d4b754.png)

How to calculate the normalized mean and standard deviation of KMER model？The official kmer model looks like this.
![RDFB2`BCBMU0`8I36ENI1S6](https://user-images.githubusercontent.com/25764447/90237676-3f13ba80-de57-11ea-9e63-ccdb3ba68286.png)

**Comment by Chris-Kimmel** [comment]
Hi @BoredMa. Would you mind sharing where you got the official kmer model?

**Comment by BoredMa** [comment]
> Hi @BoredMa. Would you mind sharing where you got the official kmer model?

Hi, the official kmer model could be found in [here](https://github.com/nanoporetech/kmer_models)

**Comment by marcus1487** [comment]
The Tombo k-mer model is computed by taking an existing re-squiggle result (initially performed using `tombo event_resquiggle` which is less useful with current raw signal basecalling models). The values are in the approximate range -5 to 5 since Tombo uses median normalization (not pA scaled normalization).

The standard deviation is the same for all k-mers since this drastically outperforms variable SD values for the re-squiggle algorithm. When k-mer specific SD values are allowed the Tombo re-squiggle algorithm tends to "pack" signal into high SD levels producing mappings which are clearly incorrect "by eye". One can explore variable SD models by using the `tombo build_model estimate_reference` command with the `--kmer-specific-sd`.

**Comment by BoredMa** [comment]
> The Tombo k-mer model is computed by taking an existing re-squiggle result (initially performed using `tombo event_resquiggle` which is less useful with current raw signal basecalling models). The values are in the approximate range -5 to 5 since Tombo uses median normalization (not pA scaled normalization).
> 
> The standard deviation is the same for all k-mers since this drastically outperforms variable SD values for the re-squiggle algorithm. When k-mer specific SD values are allowed the Tombo re-squiggle algorithm tends to "pack" signal into high SD levels producing mappings which are clearly incorrect "by eye". One can explore variable SD models by using the `tombo build_model estimate_reference` command with the `--kmer-specific-sd`.

Thank you for the reply, please correct me if I am wrong.
Tombo doesn't use the official kmer model instead of using the results from command `tombo event_resquiggle`. The mean of kmer was taken from a group of raw signals assigned to the same kmer in re-squiggle step. The standard deviation was the mean of all standard deviation over each kmer. Thus, different samples would produce different kmer model which is used to transform reference sequence to expected current level.

I am confused about this when you mentioned:
> When k-mer specific SD values are allowed the Tombo re-squiggle algorithm tends to "pack" signal into high SD levels producing mappings which are clearly incorrect "by eye".
Could you explain to me some conceptions, like "High SD levels", Is SD an abbreviation for standard deviation？

**Comment by marcus1487** [comment]
I should have included a bit of background on this explanation. The k-mer model included with Tombo was originally constructed by using the `event_resquiggle` method. This is the same algorithm found in nanoraw which was the precursor to Tombo. This estimated model is then included with Tombo for use in the standard resquiggle algorithm.

The canonical bases k-mer model included with Tombo is very similar to the "official" k-mer model linked here. The main difference between the two k-mer models is scaling. The Tombo model uses median and MAD (median absolute deviation) scaling while the official model uses pA (picoamp) scaling. The pA scaling is a bit misleading though since pA levels vary from pore to pore and over a run, so these pA values must be scaled and shifted to match an idealized pA range, which is accomplished with median scaling followed by fitting to the idealized pA scaling. The raw pA values obtained by scaling using the range, digitization and offset values from the FAST5 file are not comparable between reads even within the same run. These factors are the reason Tombo uses median scaling.

For the SD (yes this is an abbreviation for standard deviation), these are actually the standard deviation of the mean currents across different reads assigned to the same reference location (and then aggregated by k-mer). These values are then aggregated across k-mers by taking the median to obtain the constant SD for the whole model. As noted one could explore models variable SD across different k-mers with the options mentioned above.

I had a look back at the constant vs variable SD analysis and for DNA the differences were actually minimal, but the constant SD model slightly outperformed the variable SD model for known bacterial methylation detection. RNA was where the "signal packing" occurs. Basically, the penalty for slightly deviating segments of signal is lower at a reference position with a higher SD, so noisier RNA signal tends to get packed into reference positions with a higher SD even though the signal levels appear to fit better into neighboring positions. This is likely an artifact of the resquiggle algorithm. We hope to address this in a future signal mapping package (which would also fix a number of other problems with Tombo).

**Comment by BoredMa** [comment]
Thank you very much, what you said helps me a lot!
