### ISSUE TITLE
minimap2/mappy parameters

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#28]
Hi again,

While I am working on #27, I also have other thoughts.

I'd love to be able to have more control over the mapping step. When using the older version of Tombo I have, the default parameters for minimap2 results in almost 90% of reads not aligning whereas I can get 40% to align across most of their length using BLAST -- and can get partial alignments for nearly all of the reads.

I suppose one way to increase the sensitivity would be to provide the minimap2 index myself with optimized parameters -- any suggestions on k, w? Nonetheless, there still would be no way to pass mapping/alignment parameters.

Are there plans to allow parameter tuning? Is there any reason to not allow users to pass Tombo the already-minimap2-mapped (or otherwise mapped) reads?

Best,

  John

**Comment by marcus1487** [comment]
The biggest issue here is linking the mapped reads to the raw fast5s. I converted to mappy in this release for several reasons. The main ones are that passing an executable as an option caused a lot of headaches and always felt wrong and the other reason was that mappy loads the genome once and is then able to iterate over single reads which is much cleaner. In all previous versions, reads were batched in the mapping step and then made a system call to a mapper that had to load the genome for each batch. 

In terms of allowing alternative parameters I would be open to this, but I don’t think I want to change the interface to take say a SAM file of mappings. I think this opens the door to far too many user issues since the linked fast5 file would have to be contained in the mapping’s in some consistent way. 

If blast or another mapper has a good python api I could look into emulating the mappy functionality in tombo. Here is the function in the code that would need to be emulated for another mapper:
https://github.com/nanoporetech/tombo/blob/1.2/tombo/resquiggle.py#L875

**Comment by marcus1487** [comment]
One other point that I will add here on handling different mapping settings is that Tombo does not work with spliced alignments. This would be another reason I have been hesitant to allow users more access to the mapping commands. I don't want users to mistakenly expect spliced mappings to be correctly handled by Tombo. I have added [a note on processing RNA data to the docs](https://nanoporetech.github.io/tombo/rna.html), but I hope to provide a simpler framework for RNA processing soon. Though this framework would still require the signal level analysis of Tombo within a transcriptome (not genome) framework.

**Comment by JohnUrban** [comment]
Thanks for your thoughts. I think providing the minimap2 index helped me here --

I showerd the difference between the older and newer tombo versions in #27 -- and reproduced here..
Old:
```
Correcting 10303 files with 1 subgroup(s)/read(s) each (Will print a dot for each 500 reads completed).
....................
Failed reads summary (9521 total failed):
        Alignment not produced (if all reads failed check for index files) :    6782
        No valid path found through raw signal of long read :   641
        No valid path found through raw signal of short read :  563
        No valid path found through start of raw signal :       1477
        Read event to sequence alignment extends beyond --bandwidth :   5
        Read sequence from SAM and cooresponding cigar string do not agree. :   47
        Too little signal around event-aligned genomic deletion :       6
```

New:
```
Correcting 10303 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).
.........
Failed reads summary (6828 total failed):
        Alignment not produced :        6782
        Not enough raw signal around potential genomic deletion(s) :    3
        Poor raw to expected signal matching :  25
        Poor raw to expected signal matching at read start :    14
        Read event to sequence alignment extends beyond --bandwidth :   4
```
You correctly pointed out that the newer version improved in the Tombo steps -- the same number of reads failed to map.

I have no tried the newer Tombo with providing a minimap2 index with smaller kmer and window parameters used: ```minimap2 -k 5 -w 5 -d minimap2.idx ${GENOME}```

It seems to have improved the outcome for minimap2 -- at least in terms of number of mapped reads.

```
Correcting 10303 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).
.........
Failed reads summary (2356 total failed):
        Alignment not produced :        2182
        Not enough raw signal around potential genomic deletion(s) :    17
        Poor raw to expected signal matching :  119
        Poor raw to expected signal matching at read start :    30
        Read event to sequence alignment extends beyond --bandwidth :   8
```

Do you think fooling around with some of the resquiggle options can help w/ ```Poor raw to expected signal matching```, ```Poor raw to expected signal matching at read start```, etc?
e.g. ```--segmentation-parameters``` or ```--signal-align-parameters``` or ```--fit-scale-per-read``` or ```--outlier-threshold``` ....

**Comment by marcus1487** [comment]
That is great that the minmap2 index is able to modify the mappable reads! I think I will consider that a solution for the central point of this issue. The only concern I have is that I am initializing the mappy aligner using the "map-ont" preset ([here](https://github.com/nanoporetech/tombo/blob/1.2/tombo/resquiggle.py#L921)), but given that the mappings are modulated I think this option might be ignored (at least partially) when the minimap2 index is provided. This might be a question for @lh3 ?

As for the parameter tuning, yes there is some potential there, but I have spent a good amount of effort tuning these parameters in this release so I think they are relatively close to the optimal settings (obviously this may not be the case for all users; so please do have a go at it!). I have not documented this (well let's just consider this here my documentation), but tuning the parameters is carried out using the [`tombo/scripts/debug_params.R`](https://github.com/nanoporetech/tombo/blob/master/scripts/debug_params.R) R script included in the repository. There is a comment at the top of the script indicating the steps to create the input to that script. This script will then produce plots like this: 

![image](https://user-images.githubusercontent.com/13755444/36229496-4422d0fa-118c-11e8-9802-e95c90c7587e.png)

In these plots each point is a read and it's y-value is the mean absolute value(z-score) across all bases using the standard model (and the indicated re-squiggle parameter). Each tuning pdf has two pages, where the second page shows only those reads passing the filter thresholds for all parameter values tested in this batch (and thus is usually the one to use; it should probably be the first plot come to think of it). This particular example plot shows that smaller values are better for the running_window parameter for this set of DNA test reads (ultimately resulting in that default parameter being set to 5 [here](https://github.com/nanoporetech/tombo/blob/1.2/tombo/_default_parameters.py#L28)).

One important note is that these parameters can change both the mean signal its as well as the number of reads passing filter thresholds (hence the two pages of the PDF). Reads that fail due to the "Poor raw to expected signal matching" error are actually set by the last `--signal-align-parameters` values (mean signal segmentation half-normal score threshold). Thus setting this value to a very large value will allow all reads to produce valid re-squiggled results. These reads were filtered for a reason though, so they may negatively effect downstream results. 

The "Read event to sequence alignment extends beyond --bandwidth" error threshold is set [here](https://github.com/nanoporetech/tombo/blob/1.2/tombo/_default_parameters.py#L51) (not accessible on the command line), but turning the bandwidth parameter (third value to `--signal-align-parameters`) way up should allow most all reads to pass this filter. Note though that increasing the bandwidth will increase the run time. Similarly the "Not enough raw signal around potential genomic deletion(s)" error can be mostly bypassed by setting [this parameter](https://github.com/nanoporetech/tombo/blob/1.2/tombo/_default_parameters.py#L54) to 0.

I generally turn these parameters up during tuning and then dial them in once I have tuned the other "fitting-relevant" parameters. I hope this is helpful!

**Comment by marcus1487** [comment]
P.S. The red and orange dots on the plot are the median and mean values respectively for each parameter in the batch. The black line is set to the minimum median values across all tested parameters in the batch.

**Comment by JohnUrban** [comment]
Great post! I will need time to digest it. Thanks for taking the time to explain.

**Comment by lh3** [comment]
@marcus1487:

> The only concern I have is that I am initializing the mappy aligner using the "map-ont" preset (here), but given that the mappings are modulated I think this option might be ignored (at least partially) when the minimap2 index is provided.

K-mer length and window size in the prebuilt index will override the two parameters you use when you create a `mappy.Aligner` object, if I am right.

@JohnUrban what sequences are you aligning? Why the sequence divergence is that high?

**Comment by marcus1487** [comment]
Thank you @lh3 for confirming that this is the expected behavior for mappy. As this was the main concern in this thread I think we can consider this issue closed.

**Comment by JohnUrban** [comment]
It looks like if I use minimap directly and mess around with some mapping parameters, such as "-s" -- I can get more valid alignments. Any chance Tombo might get some hidden options for advanced users that allows passing alignment parameters to minimap2? 
(hidden b/c I know there were some reservations about this)

**Comment by JohnUrban** [comment]
My apologies on the last 2 comments.

I just realized that I began mapping to a slightly different reference since my initial comments far above.

Using the older reference I get the same results.

**Comment by marcus1487** [comment]
I just wanted to leave a note here that you can edit to tombo code, re-compile (or install via `pip install -e .`) and test out different minimap2 mapping parameters. [Here is the place in the Tombo code](https://github.com/nanoporetech/tombo/blob/1.2.1.2/tombo/resquiggle.py#L1094) to change the parameters. The minimap2/mappy documentation for this line can be found [here](https://github.com/lh3/minimap2/tree/master/python#class-mappyaligner).

**Comment by DelphIONe** [comment]
Just in case : in version 1.5.1 is the line 2031 of resquiggle.py script that needs to be modified.
