### ISSUE TITLE
interpretation of tombo results

### ISSUE THREAD

**Issue by lucio-cyber** [nanoporetech/tombo#285]
Hi Marcus, I launched Tombo's Resquiggling as follows: "tombo resquiggle fast5 genome.fa - - processes - - ignore-read-locks - - overwrite" and in the end he tells me this: "
******************** WARNING ********************
	Unexpected errors occured. See full error stack traces for first (up to) 50 errors in "unexpected_tombo_errors.7891.err"
[16:20:37] Final unsuccessful reads summary (21.6% reads unsuccessfully processed; 3102793 total reads):
    14.5% (2074527 reads) : Alignment not produced                                                          
     7.2% (1025976 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`) 
     0.0% (   1316 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
     0.0% (    948 reads) : Read event to sequence alignment extends beyond bandwidth                       
     0.0% (     13 reads) : Unexpected error                                                                
     0.0% (     13 reads) : Read failed sequence-based signal re-scaling parameter estimation.              
[16:20:37] Saving Tombo reads index to file.”
Can I consider that the process was successful since only 3 million did not go well? (among other things, in the fast5 file I can't find any index or RawGenomeCorrected)
It doesn't give me the RawGenomeCorrected, it appears in the home "unexpected_tombo_errors.7891.err" where there are various errors: " BaseCalled_template:::fast5_single/1436/94848c5b-8322-4cd6-9ce2-1597560219b8.fast5
:::
Traceback (most recent call last):
  File "/tank/home/sasha/miniconda3/envs/deepsignalenv/lib/python3.6/site-packages/tombo/tombo_helper.py", line 94, in banded_traceback
    return c_banded_traceback(*args, **kwargs)
  File "tombo/_c_dynamic_programming.pyx", line 305, in tombo._c_dynamic_programming.c_banded_traceback
NotImplementedError: Read event to sequence alignment extends beyond bandwidth
tombo.tombo_helper.TomboError: Read event to sequence alignment extends beyond bandwidth
IndexError: index 455 is out of bounds for axis 0 with size 455"
The thing that worries me most is that 1 million reads, because for the previous 2 million it didn't produce a significant alignment; in addition, as I said, RawGenomeCorrected does not appear. Can I ignore that million and move on or should I raise it ? 
Can i ignore these "unexpected_tombo_errors.7891.err" and move on ?

**Comment by marcus1487** [comment]
21.6% of reads failing is not ideal, but this is highly dependent upon the sample as to whether this is considered a success.

For your question concerning "in the fast5 file I can't find any index or RawGenomeCorrected", I'm not sure exactly what you mean. Are you saying the RawGenomeCorrected group is not found in the failed reads? If so that is expected. Failed reads will also not appear in the tombo index file.

For the ~1 million reads failing due to `Poor raw to expected signal matching`, this is not all that uncommon, and the expected proportion of reads with this failure mode is again highly dependent upon the sample. These reads should appear in the tombo index as well as containing the RawGenomeCorrected in the FAST5 file. You could use the TomboReads API to extract all signal matching scores to determine if a change to the threshold is warranted for your sample. This is not something for which tombo has a built in command line tool for thought (that I can remember right now at least).

For the reads with the unexpected errors, there are very few of these (13 out of 15 million reads) so I would suggest it is safe to ignore these. There seem to be some edge cases that Tombo does not handle well. There are several issues related to these issues, but I unfortunately don't have the time to track down these issues at this time.

**Comment by lucio-cyber** [comment]
When I say that I do not find either the index or the - - corrected-group RawGenomeCorrected I am not referring to failed reads but to successful ones.
If 21.6% are failed reads I can't figure out where he put the successful reads and then the remaining percentage.

**Comment by marcus1487** [comment]
That is certainly not expected. All successfully processed reads should contain the RawGenomeCorrected slot in the FAST5 (under analysis group) and be included in the tombo index. By what method have you confirmed that a successfully processed read has not been entered in the tombo index and not had the RawGenomeCorrected slot written?

I'm not sure I understand what you mean by "If 21.6% are failed reads I can't figure out where he put the successful reads and then the remaining percentage.". Could explain in more detail what you are looking for what you have tried in detail (provide code examples ideally).

**Comment by lucio-cyber** [comment]
I can't find neither the - - corrected-group RawGenomeCorrected nor the index for successful reads.
Is there a method to do this?

**Comment by marcus1487** [comment]
Find documentation for the Tombo FAST5 format as well as the Tombo index file [here](https://nanoporetech.github.io/tombo/resquiggle.html#tombo-fast5-format). 

If you have tried a specific method to identify these storage locations and are getting unexpected results, please post the exact code used the expected result and the actual result.

**Comment by lucio-cyber** [comment]
I was able to find RawGenomeCorrected in fast5 files using h5dump, and it is named “RawGenomeCorrected_000” and not “RawGenomeCorrected_001”. I think that's fine too, right?

**Comment by marcus1487** [comment]
The default value for this slot is `RawGenomeCorrected_000` so that is correct. See `tombo resquiggle -h` for more details on the parameter.

**Comment by lucio-cyber** [comment]
Thank you so much Marcus for helping me.
Best Regards
Lucio
