### ISSUE TITLE
Requires Python2.7

### ISSUE THREAD

**Issue by rfinkers** [nanoporetech/tombo#3]
Dependency on "import option_parsers" in line 3 of tomba, which is not available anymore in python 3.

**Comment by wdecoster** [comment]
I don't believe there is a good enough reason to start a new project exclusively for Python2.7, aren't there alternatives for "option_parsers"?

**Comment by rfinkers** [comment]
No, I do not propose this and it is actually the opposite. It seems this code requires python 2.7 and does not work with python 3.0. If that is true, than it is a suggestion for the documentation.

**Comment by marcus1487** [comment]
Yes, this should be in the documentation. I will add a note in the documentation for this shortly.

For the "option_parsers" point, this is actually in internal module within the tombo framework. So that is simply the first item hit which does not compute in python3. Tombo is derived from the nanoraw framework and so the code base is about 2 years old now. There is a decent amount of work to convert tombo to a python3 framework, so this is not on the immediate todo list for tombo at this time.

**Comment by marcus1487** [comment]
Fixed in 03d39b69d761e5a6b73ff1783236a91da0d7ed51
