### ISSUE TITLE
resquiggle silent core dump when run twice simultaniously against the same files...

### ISSUE THREAD

**Issue by nickschurch** [nanoporetech/tombo#30]
Don't ask me how and why but I discovered recently that if you have two tombo resquiggle jobs running simultaneously against the same fast5 files they core dump silently (in that they appear to exit cleanly).

Quite possible the correct response to this 'issue' is 'don't be so stupid as to do that then!' (a sentiment I'd heartily agree with), but it'd be nice if it failed noisily so downstream bits of pipelines know about it.

Difficult to say exactly where is fails because there's no error message, just sudden cor.xxxxxx files.

**Comment by marcus1487** [comment]
So I have actually thought about this a bit, as it has happened to me as well. Long story short I think your suggested response may be the official advice. The other solutions I have thought of all seem like they might cause more headaches and would likely only partially solve the issue.

The main solution I thought of was at the beginning of a run I delete the tombo index file. I could write (touch) a similar file indicating that the specified set of reads is currently being processed, so that any further Tombo call would not be allowed to begin. There are 2 main issues I see with this. First, if Tombo does exit from the main thread unexpectedly then this file would persist (possibly bypassed with some try, catch, finally logic) and need to be manually removed later (but this could be included in the error message to make it a bit easier on users. something like "if you are sure there are no other Tombo processes running delete the .fast5_dir.tombo_processing file"). The second, I think larger issue here is that this only partially solves the problem. Tombo searches the specified directory recursively, and so it is possible that two Tombo processes would be pointing to the same FAST5 files, but starting from a different base directory. Thus my suggested solution would still produce the segfaults you mentioned previously. So this really just swaps one "don't do that stupid" scenario for another.
 
I think it comes down to the fact that I can't really control a completely independent process from accessing the same files at the same time. It would be nice if `h5py` would catch such errors, but I understand that catching a low level segfault would be quite tricky. I don't think there is a good solution to this issue unfortunately aside from "don't do that".

**Comment by nickschurch** [comment]
I agree.

My only real suggestion is that if tombo were to die in a noisy way when
pipelines that monitor jobs for clean exit status would at least be able to
catch that something had gone wrong and flag it up for people to rerun in a
less stupid way...

**Comment by marcus1487** [comment]
That is certainly fair, but I think I may have broken this idea at a much more fundamental level. When there is some real fatal Tombo error I print a nicely formatted error message and then exit via a clean `sys.exit()` which will look like a clean exit to most pipeline software. The reason I think this is a valid result is two-fold. First when an ugly stack trace is output the clean error message is often lost in the shuffle. Second, this is really no different than all reads failing via the lack of an alignment. This clearly indicates that something is wrong, but Tombo ran correctly and processed all reads as requested. So is that an error that should throw a failed completion any more than one of these error modes? If so what percentage of failed reads should trigger a failed run? Anyways I set Tombo up to work with human read-able output and given the many different failure modes I think trying to decide when a pipeline should proceed (at this point) should take some human intervention. I hope this seems fair.

**Comment by marcus1487** [comment]
Okay so for the default behavior of Tombo to return a `0` exit code, I do now think that is wrong upon further reflection. I will change [this line](https://github.com/nanoporetech/tombo/blob/master/tombo/tombo_helper.py#L90) to `sys.exit(1)` in the next release, which should still exit silently, but also return a failed exit code (good thing I cleaned up warning and error message handling in this release ;).

I am still conflicted about how to handle this particular error case though, as it is quite hard to ensure correct handling without also creating a number of other headaches. I will consider a solution for this in the future though.

**Comment by nickschurch** [comment]
sys.exit(1) seems reasonable to me by I can see where your confict is
coming from and I reckon you've though about it quite a lot more than me
already it seems! I quite like the idea of a lock file and quite a lot of
packages use this approach. Personally I don't think its a headache to have
to remove this lock manually after something goes wrong - but again its a
perspective.

Whatever your final choice here, I would suggest a warning in the
documentation though explicitly stating that running two instances of
resquiggle on the same files at the same time is a ad idea - might
hopefully stop anyone else falling into the same trap...

**Comment by wdecoster** [comment]
Would a temporary file in /tmp/ make sense, telling the script which folder Tombo is already running on? Cleaned up at every exit (whether expected or not).

**Comment by marcus1487** [comment]
I will definitely add a note in the documentation warning against two separate re-squiggle commands at the same time.

I do think some type of lock file is the right solution. I'm not sure about the /tmp/ file solution. I think the name of the file would have to indicate the full path to the locked directory. One fixed name file in /tmp/ would not work as I wouldn't want multiple valid (analyzing different runs) re-squiggle processes accessing that file at the same time. I wouldn't want the filename to be random since it would be hard to ensure I found it correctly from another run. I guess a hashed version of the full path might work.

This still comes back to my concern that if you have one re-squiggle run pointing to a higher level and a second running on a subdirectory they could still produce these file access clashes, so any of these are partial only solutions. I think the full solution might be to put a lock on each recursive sub-directory for a run. Then if these were left from an unexpected crash a I would have a command line prompt to ignore these lock files during processing if the user is sure there is not another tombo processing running. I'll think about this a bit further, but I think I should be able to implement something here.

**Comment by marcus1487** [comment]
I decided to add the lock files to each directory that is touched by a re-squiggle command. These files are hidden files stored alongside each directory in the follwing format: ".[directory_name].tombo.lock" . This way it will not matter if a new re-squiggle command is called on a sub- or super-directory of a concurrent call to the same set of reads. The `--ignore-read-locks` flag has been added to ignore these lock files if a run should quit unexpectedly and not clear the locks (this should be very very rare).
