### ISSUE TITLE
Unexpected error：ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by Derryxu** [nanoporetech/tombo#334]
1. output informatin:
tombo resquiggle --processes 40 --basecall-group Basecall_1D_002 --corrected-group RawGenomeCorrected_002 --overwrite data/guppy/ data/Arabidopsis_thaliana.TAIR10.cdna.all.fa
[16:02:11] Loading minimap2 reference.
[16:02:13] Getting file list.
[16:02:13] Loading default canonical ***** RNA ***** model.
[16:02:14] Re-squiggling reads (raw signal to genomic sequence alignment).
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 869/869 [00:11<00:00, 74.78it/s]
******************** WARNING ********************
	Unexpected errors occured. See full error stack traces for first (up to) 50 errors in "unexpected_tombo_errors.2311.err"
[16:02:25] Final unsuccessful reads summary (100.0% reads unsuccessfully processed; 869 total reads):
    91.4% (    794 reads) : Unexpected error                                                                
     8.6% (     75 reads) : Alignment not produced                                                          
[16:02:25] Saving Tombo reads index to file.

2. unexpected error：
BaseCalled_template:::data/guppy/workspace/W_003002_20180301_FAH54216_MN23410_sequencing_run_20180301_FAH54216_VIRcomp_2928_DRS_88257_read_47_ch_192_strand.fast5
:::
Traceback (most recent call last):
  File "/home/xujr/anaconda3/envs/nanom6A_env/lib/python3.7/site-packages/tombo/resquiggle.py", line 1570, in _resquiggle_worker
    map_res = adjust_map_res(map_res)
  File "/home/xujr/anaconda3/envs/nanom6A_env/lib/python3.7/site-packages/tombo/resquiggle.py", line 1523, in adjust_map_res
    map_res.raw_signal, DEFAULT_STALL_PARAMS))
  File "/home/xujr/anaconda3/envs/nanom6A_env/lib/python3.7/site-packages/tombo/tombo_stats.py", line 313, in identify_stalls
    stall_metric[:] = np.NAN
ValueError: cannot convert float NaN to integer

**Comment by marcus1487** [comment]
I believe this is an issue with numpy >=1.20. Try downgrading and re-running. `pip install numpy<1.20`

**Comment by Derryxu** [comment]
> I believe this is an issue with numpy >=1.20. Try downgrading and re-running. `pip install numpy<1.20`

Thank you very much. It's very helpful.

**Comment by johnmalib** [comment]
The ValueError: cannot convert float [NaN to integer](http://net-informations.com/ds/err/nan.htm) raised because of Pandas doesn't have the ability to store NaN values for integers. 

From Pandas v0.24, introduces Nullable Integer Data Types which allows integers to coexist with NaNs. This does allow integer NaNs . This is the pandas integer, instead of the numpy integer.  So, use Nullable Integer Data Types (e.g. Int64).

`df['x'].astype('Int64')`

NB: You have to go through numpy float first and then to nullable Int32, for some reason.

Another solution is Using numpy.nan_to_num().  The numpy.nan_to_num() returns an array or scalar replacing Not a Number ( Not A Number ) with zero, positive_infinity with a very large number and negative_infinity with a very small (or negative) number.

If you are not satisfied with the above solutions, you need to say what you want to do with NANs . You can either drop those rows df.dropna() or replace nans with something else (0 for instance: df.fillna(0) )
