### ISSUE TITLE
resquiggle: ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by ronicaa** [nanoporetech/tombo#369]
Hi, I have trouble in numpy version when trying to resquiggle raw signals using tombo. 

When I first try `tombo resquiggle`, my numpy version is 1.21.2, and there are errors "ValueError: cannot convert float NaN to integer" just like #334  and #341. Then I uninstall v1.21.2 and install v1.19.5 using `pip3 install "numpy<1.20"`. 

However, new error appeared on my second attempt. The new error message is "ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject". I google it and its answer is to update the numpy version to 1.20.1…

So now, both the numpy version >=1.20 and <1.20 cause ValueError for me. Could you help me to solve this problem? Thank you for your help in advance!

**Comment by ronicaa** [comment]
I create a new conda environment with python==3.6 and numpy==1.19.5, and those errors are fixed. It seems to be the python 3.8.8 version problem.

**Comment by rowanhowellGE** [comment]
Hi,

Just to jump in here, I got a very similar error using python 3.9 and numpy 1.23:
`File "/opt/conda/bin/tombo", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/tombo/__main__.py", line 234, in main
    from . import _preprocess
  File "/opt/conda/lib/python3.9/site-packages/tombo/_preprocess.py", line 24, in <module>
    from . import tombo_helper as th
  File "/opt/conda/lib/python3.9/site-packages/tombo/tombo_helper.py", line 33, in <module>
    from ._c_helper import (
  File "tombo/_c_helper.pyx", line 1, in init tombo._c_helper
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`
This was fixed by rolling back to python 3.7.13 and numpy 1.21.6. Seems like some issue entered between python 3.7 and 3.8.
