### ISSUE TITLE
Question about latest --single-read-threshold defaults.

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#40]
Hi Marcus,

It looks like you made a change for defaults for ```--single-read-threshold``` in ```test_significance```.  

It used to say ```p-value:0.01; likelihoodratio:0.5```.
Now it says: ``` sample comparison:0.1; de novo:0.5; likelihood ratio:0```.

I suppose ```p-value``` has been expanded to ```de novo``` and ```sample comparison``` -- any reason to make the significance threshold higher (0.01 to 0.1 or 0.5)? What gives a likelihood ratio of 0? In general, I'd like to mess around with this option/these parameters b/c my results seem to suggest 50-100% of the majority of bases in my sample are modified when I am expecting only a subset to be modified and <<< 50% of each position. This seems like the option to mess around with to affect the fraction wig -- correct?

1.2
```
P-value or log likelihood ratio threshold when
                        computing fraction of significant reads at each
                        genomic position. Default: p-value:0.01; likelihood
                        ratio:0.5
```

1.2.1
```
P-value or log likelihood ratio threshold when
                        computing fraction of significant reads at each
                        genomic position. Default: sample comparison:0.1; de
                        novo:0.5; likelihood ratio:0
```

Best,  

John

**Comment by marcus1487** [comment]
Yes these default values were changed due to observations from internal validation samples. These values gave better results in identifying known methylation sites. For the de novo and sample comparison method, yes these both return p-values, but it looks like different default p-value thresholds were appropriate here. The alternative model comparison method results in *log* likelihood ratios. I should probably change that default message from likelihood ratio to alternative model comparison since the message notes that the value is log likelihood ratios above.

As for looking into this parameter for tuning a specific modification detection sample, that is likely a good idea. You should look into the new `plot_per_read_roc` command which produced a distribution of test statistics at known true and false positive sites (you could spoof this command with a dummy motif if you don't have a known modification motif). Here is the [new part of the docs](https://nanoporetech.github.io/tombo/plotting.html#roc-curves) describing this new plot. These default thresholds certainly may not be ideal for all experimental setups.

I hope this helps.

**Comment by JohnUrban** [comment]
Many thanks Marcus. I believe this helps. I will close.
