### ISSUE TITLE
question re: est_alt_reference

### ISSUE THREAD

**Issue by niphilli** [nanoporetech/tombo#45]
I have amplicon data with and without a modified base (amplicon length ~2kb).  When I resquiggled the data, I used a reduced kmer via the --minimap2-index option, and the data can be used to generate a est_reference model with reduced upstream and downstream bases.  However, with est_alt_reference, I am getting the following error based on kmer observations:
![image](https://user-images.githubusercontent.com/19784719/37831252-cfa0d0d4-2e72-11e8-9166-91d849e5f38a.png)
Reducing --minimum-kmer-observations does not resolve the issue.  Can kmer upstream and downstream base number be used in this command? I do not see it as an option in the help documentation.  Any suggestions?  Thanks a million!

**Comment by marcus1487** [comment]
The k-mer size for this command is determined by the canonical/control model that is provided. There are several reasons for this choice. First is that the alternative model takes the canonical distribution for k-mers that don't contain the "swap base". The second reason is that the purpose of the alternative model is to compute a likelihood ratio. This requires that the k-mer models used are composed from the same k-mer length and central base registration.

Thus I think the options here are 1) the k-mer size for the canonical model should be reduced further (although obviously this may reduce the effectiveness of the model), 2) the alternative sample should be sequenced deeper to cover each k-mer with more reads or 3) that a reference sample with larger k-mer diversity would need to be used so that the alternative model can be estimated with a sufficient k-mer diversity coverage.

I hope this help!

**Comment by niphilli** [comment]
Very helpful. Thank you again!
