### ISSUE TITLE
Outputting p-values

### ISSUE THREAD

**Issue by clarepacini** [nanoporetech/tombo#51]
Hi,
I was looking at the paper for Tombo that discusses the option of outputting p/qvalues with write wiggles. However, I don't see it as an option in the current Tombo manual. Is there a way to output p or q-values corresponding to the detection of modified bases in Tombo?

Thanks

Clare

**Comment by marcus1487** [comment]
The [nanoraw preprint](http://biorxiv.org/content/early/2017/04/10/094672) is the basis for the Tombo framework, but one of the major changes between these two methods is the modified base testing methods. In nanoraw, the only testing method available was to compare reads from a sample of interest with a sample from the same reference, but with only canonical bases (e.g. PCR). This was performed by using either a two sample t-test or u-test resulting in a p-value.

In Tombo, this method has been replaced by [3 different methods](https://nanoporetech.github.io/tombo/modified_base_detection.html), though all of these methods differ from the nanoraw method in that test are performed on a per-read basis. Then in order to look at modified base content across the genome a global per-read threshold is applied and the fraction of reads indicating a modified base is reported at each genomic position.

There were several reasons for this change, but one of the major reasons is that the p-values reported by nanoraw were very related to sequencing depth (more reads preferences for a significant result) whereas the Tombo fraction of modified reads method is much less dependent upon read depth.

You can plot per reads statistic with the associated p-values (or log likelihood ratios for alternative base method) for each read at a genomic location using the [`tombo plot_per_read` command](https://nanoporetech.github.io/tombo/plotting.html#per-read-plotting).
