### ISSUE TITLE
comparison of the three tests

### ISSUE THREAD

**Issue by khatamimaryam** [nanoporetech/tombo#52]
Hello Marcus

I have a question. 

For a set of reads that only contain 5mC methylation, the result of the `alternate-bases 5mC` indicates all methylated Cs. By using `write-wiggles` I get the `fraction` of modified reads for each methylated C too.

But what is the result of the other two tests on the same set of data? I see that the resulting wig files show all the bases (with corresponding `fraction`s), while I know only Cs have been methylated.

Thanks.

**Comment by marcus1487** [comment]
For the other 2 tests (de novo and canonical sample comparison) there is no indication as to which of the four bases is modified. Additionally, for these two test the maximal test values not guaranteed to center on the modification of interest since the shifts in signal occur at different locations relative to the actual modified base for each sequence context. This is also the reason that the Fisher's Method context parameter is provided; in order to better center the testing results on actual modified bases (though this result is still imperfect). 

This is one of the main advantages of the alternative model comparison method since the relative location of signal shifts to a modified base are explicitly modeled. The other two methods are primarily aimed at research into unknown bases of interest for these reasons.

I hope this helps clear up the results from the Tombo testing results.
