### ISSUE TITLE
Poor raw to expected signal matching

### ISSUE THREAD

**Issue by dorothyzh** [nanoporetech/tombo#55]
Now I have one fast5 read data, I generate the fastq from this fast5 and convert it into fasta as reference. Then use Tombo to align the fast5 to this reference. Because the content in the reference file is exactly the sequence in the fast5, why this action is failed?  I've tried some reads, some are succeed while others were failed. 

huans-iMac:HKBU_PC1_20180330_FAH70397_MN26164_sequencing_run_20180330_63577_read_671_ch_181_strand.fast5 huanzhong$ tombo resquiggle --rna fast5/ test.fa --processes 8 --overwrite
Loading minimap2 reference.
Getting file list.
Estimating global scale parameter
******************** WARNING ********************
	Few reads contain raw signal for global scale parameter estimation. Results may not be optimal.
Correcting 1 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).

Failed reads summary (1 total failed):
	Poor raw to expected signal matching :	1

###test.fa
>45aab8d5-102a-40c0-8204-0652b6105aae runid=8c18dda2e137cd56ce420a83410c2a16bf3c25d0 read=671 ch=181 start_time=2018-03-30T06:10:12Z
CGCCATTGCCATTTCTAAAATTGTCGTCTGCTGTCTCTCTTCGCGGGCGACGAAAATCTCCCATCCCATCATCATCCCTCGTTAACCACTATTTCCTCCCACTCCCATGCCCTA

**Comment by marcus1487** [comment]
This failed read mode indicates that the raw signal does not match the sequence above an expected threshold. This is somewhat analogous to the q-score for a read. Reads produce basecalling with varying results and that is why you are most likely getting this error mode for some reads. This threshold for calling a read failed due to raw signal can be increased using the fourth value to the `--signal-align-parameters` argument to `resquiggle` (note you can see the other defaults from the help text). This may not produce the best raw signal assignment results though.

**Comment by dorothyzh** [comment]
Thanks a lot~~  yes, when I set the fourth number from 1.75 to 4.75, it works


******************** WARNING ********************
	Few reads contain raw signal for global scale parameter estimation. Results may not be optimal.
Correcting 1 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).

All reads successfully re-squiggled!

**Comment by marcus1487** [comment]
In the recent release (version 1.3), the parameter referenced here has been refactored into it's own `resquiggle` command line option, `--signal-matching-score`. A filter (`tombo filter raw_signal_matching`) has also been added to apply a new lower threshold for this parameter after the `resquiggle` command has completed. In order to raise the threshold for this value in the current Tombo version, run `tombo filter clear_filters` followed by a `tombo filter raw_signal_matching` call. These commands should be relatively fast and allow much easier tuning for this parameter in runs moving forward.
