### ISSUE TITLE
resquiggle complaining in failed reads summary: Does not understand character buffer dtype format string ('e')

### ISSUE THREAD

**Issue by JohnUrban** [nanoporetech/tombo#56]
Hi Marcus,

Do you have any idea what to look at for this message:
```
resquiggle complaining in failed reads summary: Does not understand character buffer dtype format string ('e')
```

I've been trying to insert raw data from R7.3 as we discussed previously -- and am currently getting that message.

best,

John

**Comment by JohnUrban** [comment]
p.s. Similarly, if I've been trying it with ```event_resquiggle```, where can I look to remedy:
```Failed reads summary (1 total failed):
             'start_time' :	1
```

**Comment by marcus1487** [comment]
I have seen the `start_time` issue previously from nanoraw. [This issue](https://github.com/marcus1487/nanoraw/issues/39) may help pinpoint the problem there. For the character buffer, I am guessing that would have to do with exactly how some of the data are stored in the fast5 file.

I have unfortunately not had a ton of time to keep the `event_resquiggle` command up-to-date with other updates to Tombo. There is a chance that some of the code there is a bit outdated. If you are looking to dig into the code a bit, here are 2 pointers to the place to start in the code: [first pointer](https://github.com/nanoporetech/tombo/blob/1.2.1.2/tombo/_event_resquiggle.py#L440) and [second pointer](https://github.com/nanoporetech/tombo/blob/1.2.1.2/tombo/_event_resquiggle.py#L1007). If you uncomment these `raise` lines and run the re-squiggle command you will get more information about the first read that fails (so you may want to just process a couple reads from the `--failed-read-filename`. Hopefully that is enough to get you started, though this may be too much information.

**Comment by marcus1487** [comment]
Great! And if you do have a script to merge the R7 raw and basecalled data that would be a nice little tidbit to add to the tombo scripts if you are so inclined.

**Comment by JohnUrban** [comment]
For sure.

I should say why I am messing around with event_resquiggle. The reason is that I am assuming the R7.3 models (older 5mers, more recent 6mers) are not consistent with the standard median normalized Tombo model used to help resquiggle. Therefore, I'd need to provide my own model. However, it is unclear to me how to convert the R7.3 models into the median normalized models -- for the same reasons you didn't think applying median normalization to the events would be appropriate. Looking at Tombo, it seemed like I could use events_resquiggle to bypass the need for a model.... then maybe model_resquiggle...? Any suggestions would be helpful on that -- e.g. am I correct that event_resquiggle makes more sense than resquiggle in this scenario? do you have any suggestions on using the older R7.3 models with Tombo?

**Comment by JohnUrban** [comment]
Ultimately, I'd love to get the re-segmentation step to median normalize the R7.3 raw data, and provide re-segmented median normalized events.... and use most of the Tombo tools downstream.

**Comment by marcus1487** [comment]
You are indeed on the right track here. I don't think the models included with Tombo will work well with R7 data. Without a model, `event_resquiggle` is your best option. If you have a PCR'ed R7 sample available, I would suggest running `event_resquiggle` on that (ideally from albacore <2.0 basecalled events). Then you could estimate an R7 canonical model using the `estimate_reference` Tombo command. Then you could use Tombo as with R9 data, but providing this new reference via the (hidden) argument `--tombo-model-filename`. This option does not show up on the command line (i.e. it is not in the `tombo [command] -h` output; as I suspect it would be quite rare at this point for someone to use), but any command that takes a model in Tombo takes this argument.

**Comment by JohnUrban** [comment]
Command:
```
tombo resquiggle --overwrite --minimap2-index ${M2IDX} fast5files/ reference.fasta 
```

In terms of this issue:
```
Getting file list.
Using default canonical ***** DNA ***** model.
Estimating global scale parameter
******************** WARNING ********************
	Few reads contain raw signal for global scale parameter estimation. Results may not be optimal.
Correcting 1 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).

Failed reads summary (1 total failed):
	Does not understand character buffer dtype format string ('e') :	1
```

If I change the raw data type to np.int16 instead of np.float16, it gives a different error:
```
Getting file list.
Using default canonical ***** DNA ***** model.
Estimating global scale parameter
******************** WARNING ********************
	Few reads contain raw signal for global scale parameter estimation. Results may not be optimal.
Correcting 1 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).

Failed reads summary (1 total failed):
	Poor raw to expected signal matching at read start :	1
```

So it seems like it "fixed" the first issue -- in quotes b/c I will need away to feed it the floats if possible.
I can see that converting these floats to integers causes a poor fit to the mean and sd given by the events. Would that explain the new error?

**Comment by marcus1487** [comment]
Ah. So there are certainly some issues with exactly how the event information is stored. [Here is the line](https://github.com/nanoporetech/tombo/blob/1.2.1.2/tombo/tombo_helper.py#L1683) where I write the new Tombo "events", which should help out with how to write the R7 events data to a raw file (which I think is the np.int16 to which you are referring, but please correct if you are referring to a dtype in another location). 

For the conversion script on which I think you are working, it might also be easier to add the raw signal and needed raw attributes to the basecalled files than to add the events to the raw signal file.

**Comment by JohnUrban** [comment]
Hi Marcus,

Thanks for the link to that specific line.

Apologies for the confusion. I actually have been trying to do what you just suggested, which is to add raw signal to the basecalled fast5 files.

This would be the path in the basecalled fast5:
```
'/Raw/Reads/Read_xx/Signal'
... where xx is the number
```

When opening the fast5 in write mode, I simply do:
```
fast5['/Raw/Reads/Read_xx/Signal'] = np.array(raw, dtype=dtype)
```
Using dtype=np.float16 makes most sense, but I seem to be forced to use dtype=np.int16.

The raw data looks something like this:
```
66.125
67.125
66.812
65.125
66.125
66.188
67.25
66.312
66.812
65.062
65.75
67.312
66.0
66.812
65.875
67.0
```

**Comment by marcus1487** [comment]
The raw signal certainly should be in integers as these are the raw data acquisition values (I've seen DAC or DAQ as the name for this value). This is indeed stored as an integer. This raw signal level looks more like pA normalized data. Is this raw signal directly from that `/Raw/Reads/Read_xx/Signal` slot? I have not looked at that R7 data in a while, but I am relatively certainly that these were still stored as integers in R7 files. In any case the median normalization should be able to handle the conversion of these data to integers without much difference.

For the poor fit error, that is likely due to the default model not fitting the data well. If the models turn out to be close enough (which I am not sure about), you could consider raising the threshold for a poor fit (as described [here](https://github.com/nanoporetech/tombo/issues/55
)) and modeling from that data. Hopefully that helps.

**Comment by JohnUrban** [comment]
Well I did have some success with re-squiggle after visiting #55 as you suggested.

Maybe I will just abandon event_resquiggle then. I can use looser parameters to get an initial aligment of PCR ACGT data, then learn the model given the alignment. Then do another alignment, and update the model... etc. Maybe 5 iterations, and I will have a good R7.3 Tombo model... thoughts?

**Comment by marcus1487** [comment]
So this is one of those `Raw` slot attributes that you would need to add along with the actual raw data. Here is the [point in the code](https://github.com/nanoporetech/tombo/blob/1.2.1.2/tombo/_event_resquiggle.py#L904) where that slot is accessed. So you would need to emulate this value as well. This slot has to do with where the Events data starts within the raw signal. So for R7 events the event start time is computed in a float and so I had to do a lot of checking when reading the events table, as you can see [here in the code](https://github.com/nanoporetech/tombo/blob/1.2.1.2/tombo/_event_resquiggle.py#L912) since floats can convert to the wrong integer in some cases. 

This also means that you need to add the correct amount of data in the raw signal before this start time. Or probably just set the raw slot `start_time` to the same as the first event start time from each reads event table (I think that should work).

**Comment by marcus1487** [comment]
Your idea to get the R7 model could work as well. That might be the easier way forward.
