### ISSUE TITLE
High number of failed reads during re-squiggle & plotting issues

### ISSUE THREAD

**Issue by AnjuniPeiris** [nanoporetech/tombo#59]
Hi,
I'm having a bit of trouble with the re-squiggle algorithm. I edited the FASTQ sequence headers to begin with the FAST5 read identifier, but most of the 7167 FASTQ files I'm running fail. In addition, I get a higher number of failed reads each time I run the re-squiggle algorithm. These are the error messages for different attempts:

Correcting 7167 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).
Failed reads summary (6842 total failed):
        'pcontig_019' : 6796
        Not enough raw signal around potential genomic deletion(s) :    17
        Poor raw to expected signal matching :  1
        Poor raw to expected signal matching at read start :    12
        Read event to sequence alignment extends beyond --bandwidth :   16

Failed reads summary (5124 total failed):
        'pcontig_019' : 4741
        Not enough raw signal around potential genomic deletion(s) :    108
        Poor raw to expected signal matching :  22
        Poor raw to expected signal matching at read start :    130
        Read event to sequence alignment extends beyond --bandwidth :   122
        Too much raw signal for mapped sequence :       1

I'm not sure what the 'pcontig_019' error is referring to. These runs were for one contig (contig 19) of the rust genome I'm looking at. Any steps to fix this problem?

Also, I'm trying to use the plot_per_read to plot some base modifications. The plotting step requires a chromosome number input for the"--genome-locations" flag, but the reference genome for this rust only has contigs with contig names instead of chromosome numbers. There's no option to enter the contig names, so I was wondering if its still possible to make plots with plot_per_read using contig locations.

Thanks!

**Comment by marcus1487** [comment]
I am a bit confused by this question. When you state that most of the FASTQ files fail, do you mean they fail when you run `annotate_raw_with_fastqs` or when you run `resquiggle`? 

As for the differing failed reads summaries, the whole re-squiggle algorithm is deterministic, and so there should be no difference when run using the same reads (annotated with the same basecalled sequence) and reference. I believe the `'pcontig_019'` error has been fixed in the most recent version. Do you have the most recent version (`1.2.1.2`)?

For the `plot_per_read` question, the `--genome-locations` takes the "chromosome names" from the fasta file record lines. These do not need to be chromosome numbers in particular, but just whatever the fasta files provide as record names (text up to the first whitespace character on the record lines). So your contig names should work with for this command.

**Comment by AnjuniPeiris** [comment]
The FASTQ files failed when I ran resquiggle. The 'pcontig_019' error went away later after I installed some python requirements that were missing. I'm using tombo version 1.2.1 anyway which might be the issue.

For plot_per_read, should I put the fasta file in the --genome-locations flag, or should I make a separate file with contig names?

Thanks for the advice!

**Comment by marcus1487** [comment]
The `resquiggle` command is supposed to take FAST5 (raw read files) and not FASTQ, so `resquiggle` will not even process any fastq files in a directory. To add basecalled FASTQ records to a set of reads you can use the `annotate_raw_with_fastqs` command.

As for the `--genome-locations` flag, this option takes string arguments. Each argument is formatted (as noted in the help via `tombo plot_per_read -h`) as `chrm:position[:strand]`. So for your contig this could be run something like this: `tombo plot_per_read  --genome-locations pcontig_019 :100:+ pcontig_019 :500:- pcontig_019 :1000:+ --per-read-statistics-filename rust_results.tombo.per_read_stats`. The `chrm` values passed here should match whatever sequence record names are found in the reference FASTA you provided to the `resquiggle` commands. Just in case you are use another custom reference FASTA at a later point.

**Comment by AnjuniPeiris** [comment]
That makes sense. Thanks for your answers!
