### ISSUE TITLE
Question on raw alternate fraction and importance of coverage

### ISSUE THREAD

**Issue by russellj7** [nanoporetech/tombo#61]
Hello @marcus1487,

I'm using Tombo's provided alternative model to detect m6A modifications within a specific motif. I am using the `write_most_significant_fasta` option to write all m6A modifications across a bacterial genome, not just the most significant as described in the documentation. This leads to output with a range of raw alternative fractions. From there I can subset to just the contexts with my motif of interest.

If I'm understanding correctly, a raw alternative fraction of 1.0 indicates that all reads covering that modified position are modified (i.e. that adenine is always modified). On the other hand, a raw alternative fraction of 0 indicates that the position is never modified. My question is, what would you consider a reasonable cutoff to confidently consider a position to be modified? For example, a fraction greater than 0 or greater than 0.5?

My second question is related to Tombo's sensitivity to varying depths of sequence coverage. Should Tombo only be used to compare runs of similar coverage? For example, if wanting to compare a run with ~40x coverage to a run with ~400x coverage, would you see differences simply due to differences in coverage? For PacBio modification detection, coverage is very important. As the coverage changes, so do the number of modified motifs, so comparing runs at the same level of coverage is a necessity. 

Thank you in advance for your advice!

**Comment by marcus1487** [comment]
For the `write_most_significant_fasta` question, I am not sure I understand what you mean by using this command to output all m6A modifications as opposed to just the most significant. Are you simply setting the `--num-regions` to the length of the genome? In any case, if you are interested in outputting all of the testing results across the whole genome, the [`write_wiggles` command](https://nanoporetech.github.io/tombo/text_output.html#write-wiggles) is probably the better option. This will output just the test results in the wiggle format. Then you could extract the motif of interest positions from that file.

For the interpretation of the raw alternative fraction, your interpretation here is correct (1.0 indicates all reads are modified and 0 indicates no reads at this position indicate modified bases). I am not sure I could make a recommendation on a cutoff value for the fraction of modified bases at a genomic position. I say this since the fraction itself may be biologically meaningful. For example, a sites methylation may be linked to a SNP and so it is possible that the true fraction of modified bases at a position is 0.5 and thus using a binary cutoff is not really meaningful since the ground truth is that half the reads are modified at that genomic position. I realize that is not really a satisfying answer, but I would possibly suggest using the ranking produced by this statistic as opposed to a binary cutoff if possible.

One point I have realized recently is that the the `--single-read-threshold` is very impactful for different samples and testing frameworks. So changing some testing parameters or for certain modified bases may require changes to the default `--single-read-threshold` values. In order to test out this parameter, I have enabled the [`aggregate_per_read_stats`](https://nanoporetech.github.io/tombo/modified_base_detection.html#aggregate-per-read-statistics) command. This requires that the `test_significance` command is run with the `--per-read-statistics-basename` option set and that resulting file passed to `aggregate_per_read_stats`.

For the last question about coverage, I addressed this a bit in another issue recently ([here](https://github.com/nanoporetech/tombo/issues/60)). In short, yes coverage could certainly effect the results, but I think this effect should be minimal above a certainly level of coverage (probably >10-15X, but this has not been verified). This was one of the main reasons I chose to shift Tombo to mainly use the estimated fraction of modified bases and not combined testing values which is generally more effected by coverage.
