### ISSUE TITLE
Will tombo distinguish different RNA configuration?

### ISSUE THREAD

**Issue by haotianteng** [nanoporetech/tombo#63]
I am wondering if Tombo will distinguish the pore model used in sequencing and automatically choose the configuration? RNA sequencing has two pore models used: -200mV and -180mV, what is the default one Tombo set, or it will be automatically detected?

**Comment by haotianteng** [comment]
**Tombo runs well in -200mV RNA configuration:**
Loading minimap2 reference.
Getting file list.
Using default canonical ***** RNA ***** model.
Estimating global scale parameter
Correcting 27419 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).
...........................
Failed reads summary (4143 total failed):
        Alignment not produced :        755
        Analysis group not found at root of FAST5 :     1
        Not enough raw signal around potential genomic deletion(s) :    2
        Poor raw to expected signal matching :  1218
        Poor raw to expected signal matching at read start :    2061
        Read event to sequence alignment extends beyond --bandwidth :   106

**But it fail to resquiggle all the reads in -180mV RNA pore model:**
Loading minimap2 reference.
Getting file list.
Using default canonical ***** RNA ***** model.
Estimating global scale parameter
Correcting 77936 files with 1 subgroup(s)/read(s) each (Will print a dot for each 1000 reads completed).
.............................................................................
Failed reads summary (77936 total failed):
        Alignment not produced :        7636
        Not enough raw signal around potential genomic deletion(s) :    377
        Poor raw to expected signal matching :  45157
        Poor raw to expected signal matching at read start :    24766

**Comment by haotianteng** [comment]
I can help to add the -180mV pore model, which part of code should I looked at?

**Comment by marcus1487** [comment]
As you have correctly figured out, the default Tombo RNA model was indeed produced using 200mV RNA data. I am working on producing a 180mV RNA model and I will include that in the next Tombo release. Unfortunately, there is a bit more processing that needs to be performed in order to transform the `kmer_model` version of the model into a Tombo model. This has mostly to do with the different normalization as well as making the model work better with the re-squiggle algorithm.

I have not yet completely figured out how I would incorporate the option to run either the 180mV or 200mV model, but it may be some option similar to the albacore config settings. In the next release, I think I will make the new 180mV model the default but leave the 200mV model in the repository with a pointer as to how to access this model in the documentation.

**Comment by marcus1487** [comment]
An updated 180mV RNA model has been added as the default for processing RNA data in the recent release (version 1.3). I have left the 200mV model as part of the code base [here](https://github.com/nanoporetech/tombo/tree/master/tombo/tombo_models), but it is not accessible via the command line. To use the 200mV model in the future use the `--tombo-model-filename tombo/tombo_models/tombo.RNA.200mV.model` option for any commands requiring the RNA canonical model.

**Comment by haotianteng** [comment]
That's great! Thank you for the update.

Teng

**Comment by haotianteng** [comment]
I tried the new -180mV RNA model, and it failed on many reads, I have tested on two of our samples, and has similar results.
Here is the output, most of the reads failed because of the poor raw to expected signal matching error.
Am I using the setting wrong?

(tombo_1.3) haotianteng@Heavens:~/Tools/Albacore/Albacore_2.2.7$ tombo resquiggle --rna /media/Common_ex/20171113_RNAseq_GN131/Albacore_2.2.7/workspace/pass/ /media/Linux_ex/Nanopore_Data/RNA/Reference/S00000028.fasta --overwrite
[18:01:00] Loading minimap2 reference.
[18:01:01] Getting file list.
[18:01:01] Re-squiggling reads (raw signal to genomic sequence alignment).
100%|███████████████████████████████████████████████████████████████████████████████████████| 62642/62642 [3:18:33<00:00,  5.26it/s]
[21:19:36] Failed reads summary (62500 total failed):
        Alignment not produced :        6609
        Not enough raw signal around potential genomic deletion(s) :    547
        Poor raw to expected signal matching (revert with `tombo clear_filters`) :      50508
        Read contains too many potential genomic deletions :    2
        Read event to sequence alignment extends beyond --bandwidth :   4588
        Read failed sequence-based signal re-scaling parameter estimation. :    244
        could not broadcast input array from shape (1195) into shape (1200) :   1
        could not broadcast input array from shape (1199) into shape (1200) :   1

**Comment by marcus1487** [comment]
It is possible that the default thresholds are too stringent for your sample. This can also be a sign that the sample is highly modified or that the sample is divergent from the provided reference sequence.

In any case this latest release (1.3) has made it easier and much quicker to adjust this threshold. You can clear the filters on this run and apply a new raw signal matching threshold with the following commands:

```
tombo filter clear_filters --fast5-basedirs /media/Common_ex/20171113_RNAseq_GN131/Albacore_2.2.7/workspace/pass/ 
tombo filter raw_signal_matching --fast5-basedirs /media/Common_ex/20171113_RNAseq_GN131/Albacore_2.2.7/workspace/pass/ \
    --signal-matching-score 1.7
```

In order to identify an appropriate threshold, you can extract the signal matching scores from your run via the tombo python API with the following code:
```
from tombo import tombo_helper
run_data = tombo_helper.parse_fast5s(['/media/Common_ex/20171113_RNAseq_GN131/Albacore_2.2.7/workspace/pass/',], 'Basecall_1D_000', ['BaseCalled_template',])
all_run_sig_match_scores = [r_data.sig_match_score for chrm_strand, cs_reads in run_data.items() 
                            for r_data in cs_reads]
```

**Comment by haotianteng** [comment]
so after resetting the filter raw_signal_matching, I just rerun the re-squiggle command?

**Comment by marcus1487** [comment]
No need to re-run the re-squiggle command. The filter commands are applied to the re-squiggle results and effect only the tombo index file. The re-squiggle results are stored in the individual fast5 files even if they fail this category from the resquiggle command. For future runs this filter threshold can be set directly in the re-squiggle command as well. 

So after the filter command is applied the statistical testing or any other plotting commands can be applied to this set of reads.
