### ISSUE TITLE
question about covered positions

### ISSUE THREAD

**Issue by ma-diroma** [nanoporetech/tombo#65]
Hi,

I used `write_wiggles` function specifying `coverage` and `fraction` types. I suppose coverage output contains all the covered genomic (or transcriptomic) positions. The raw fraction of significantly modified reads is reported within fraction output file, however I see also positions with a modified fraction =0.0. I expected to find the same number of positions within the 2 files, but there are more sites within coverage file (56436875) rather than fraction file (56265076). 
Moreover, I found a huge number of positions with a modified fraction >0 (55936957), corresponding to more than 99% of covered positions (those reported in the coverage file). 
Could you please help me with these issues?
Thanks,
Maria Angela

**Comment by marcus1487** [comment]
Hi,

For your first question about the difference between the coverage file and the fraction file, this is most likely to do with the `--minimum-test-reads` value set during the `test_significance` command. Thus only genomic locations with at least this many reads will produce results in the statistics file and thus results in the output wiggle file. If this is not the issue it may be a bug.

For the large fraction of positions with a modified fraction >0, there are a couple of explanations for this. The first would be the pseudo-counts added by the `--coverage-dampen-counts` option to the `write_wiggles` function. This essentially starts each genomic location with 2 un-modified read and half a modified read. The purpose of this is to reduce false positive modification locations for lower coverage locations. This will also cause all sites to have a fraction modified >0. The second issue at play here is that the de novo significance testing method (not sure if that is what you are using here) identifies all deviations from the canonical model. Given the random fluctuation in signal this can cause at least some reads to indicate a positive identification of modified bases at any location. 

Finally, I have also recently become aware that the default thresholds do not work very well for direct RNA data. These values were used because they work well with DNA validation data sets, but would likely need to be tuned for RNA data. I discussed this issue in #64 previously.

I hope some of these pointers might help you out. Best of luck!

**Comment by ma-diroma** [comment]
Thanks for your quick reply.
About `--minimum-test-reads` option, I left the default value (1). That's why I expected to find the same number of positions in the two files, coverage and fraction.
The same for `--coverage-dampen-counts`, I left the default values. Do you have some suggestions about which ones could be better to be used for RNA analysis, based on your experience?
Numbers reported above are related to de novo detection. When I tried to use the other two methods for detection of modified bases, percentages lowered, but remaining above 50% with respect to the covered sites.

**Comment by ma-diroma** [comment]
I have another question about coverage. I aligned my sample directly using Minimap2, I counted covered positions, the number is almost twice that reported in coverage output. Is this difference due to the resquiggle process? And how is it determined?
Thanks

**Comment by marcus1487** [comment]
For the previous question about mis-matching coverage and testing results, I realized that this is actually due to the edges of each read. Due to the way reads are processed in Tombo only the mapped sequence is stored for testing (and not any surrounding sequence). The k-mer model used in testing requires several bases of context in order to look up the expected level of signal. Thus for each tested read the first and last few mapped bases do not produce testing results since an expected level cannot be obtained. This could be fixed by storing the sequence surrounding an alignment, but this would require some relatively large changes to the way sequence is stored and accessed in the code base. This does explain the difference between the coverage and testing output lengths though.

For `--coverage-dampen-counts` I think these defaults should be okay, but as noted in #64 I think the value of `--single-read-threshold` should probably be somewhere around 0.05 and 0.1.

For the differences between mapping reads directly and using Tombo, this is due to reads that failed the re-squiggle procedure at some point. The result of the re-squiggle command produces a failed reads report. Most of these errors usually occur after the mapping step and these reads will not be included in the Tombo coverage report. A summary of some of these failed read types can be found [here](https://nanoporetech.github.io/tombo/resquiggle.html#common-failed-read-descriptions) in the documentation. In my internal test I aim for this set of failed reads to be at or below 10% of mapped reads, but this could certainly be higher for some samples, especially if the sample is more divergent from the reference used. 

I hope this help and best of luck!

**Comment by ma-diroma** [comment]
Thank you! I really appreciate your help!
