### ISSUE TITLE
Output of 

### ISSUE THREAD

**Issue by Somebodyatthdoor** [nanoporetech/tombo#66]
Hi,

Sorry if this is a rather simple question, I am quite new to bioinformatics. I have been running tombo on some RNA sequences and have been trying to perform de novo base detection. After running 

tombo test_significance --fast5-basedirs _fast5location_  --statistics-file-basename _filename_

tombo plot_most_significant --fast5-basedirs _fast5location_ --statistics-filename _statslocation_ --plot-standard-model

The output pdf file looks a little strange, the raw signal does not seem to match the overlay. I am presuming I have done something wrong and would be very grateful for some advice. 
[tombo_results.significant_difference.pdf](https://github.com/nanoporetech/tombo/files/2017098/tombo_results.significant_difference.pdf)

**Comment by marcus1487** [comment]
Hi,

These certainly are quite strange signal assignments. My best guess is that these are likely assignments of signal to regions of sequence that do not actually exist in your sample. For example if you are mapping spliced mRNA to a genomic reference, you could get these types of signal assignment through introns. This can also happen around real genomic/transriptomic deletions or insertions if this was mapped to a transcriptome reference. There are some other tips on direct RNA processing [here](https://nanoporetech.github.io/tombo/rna.html) in the documentation that might be helpful.

These reads should have better signal assignment through neighboring regions, or else they would have been filtered out based on poor expected to observed signal matching. Hopefully this help!

**Comment by mw55309** [comment]
When will the recommended RNA processing pipeline be posted?

**Comment by marcus1487** [comment]
These are certainly very bad alignments in this case. It could be that this is an issue with the RNA model included with tombo, which is currently generated from 200mV data. I will have a new 180mV model included in the next release. There are also some other signal normalization and processing updates that should improve regions like this in the upcoming release. 

If you are mapping to a transcriptome reference then the recommended rna processing pipeline will not be of help here.  That processing pipeline is intended for users starting from a genomic reference and annotated genes. I will update the docs to reflect this point.

**Comment by mw55309** [comment]
Thanks Marcus :)

Is there any way we can view / export, for each position in the transcript, the values/distribution of signal at that position; and related, how do we see the expected distribution from the model?
Cheers
Mick

**Comment by marcus1487** [comment]
Hi Mick, For the signal distribution part, there is an ‘—overplot-type’ option to the plotting commands. Here are some examples of (these plots)[https://nanoporetech.github.io/tombo/plotting.html#over-plotting]. The density plot type would probably be best here. 

For genome browser text output, the write_wiggles command has a mean signal output option (docs here)[https://nanoporetech.github.io/tombo/text_output.html#write-wiggles]. I don’t have an option to output the expected model levels, but could look into adding that option later. This output might be useful since these poor fitting regions will likely have pretty flat average signal. It might give you an idea of how pervasive is this poor signal assignment. 

I will warn that these 2 commands are currently kind of slow since all plotted signal levels must be extracted from the fast5 files.

**Comment by mw55309** [comment]
Sorry Marcus, I'm not sure I understand.

What I would love is:

For each position in the transcript, for each read that aligns to that position - the signal for that read at that position.  I don't want the mean.

Basically, because you don't have good models, we are going to have to compare two samples.  So I can get a feel for the data, what I will want to do is compare the distribution of signal at each position in one sample with the distribution of signal at the same position in a different sample.  For this, I guess I will need the aforementioned data.

What is the best way to get that? (I don't want to plot it, I want the values)

**Comment by marcus1487** [comment]
Hi @Somebodyatthdoor and @mw55309 , the current release (1.4) now makes this task much more concise with a complete python API re-write. You can see that this task is essentially the first example in the API docs [here](https://nanoporetech.github.io/tombo/tombo.html#python-api-examples).

Do note here if you run into trouble with the new API. Thanks!

**Comment by marcus1487** [comment]
Also note that the [`get_ref_from_seq`](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_stats.get_ref_from_seq) function has been added to the API in order extract the expected signal levels from a bit of genomic sequence (as this was requested above as well). 

I'll also note here that the RNA re-squiggle procedure and models are drastically improved with this release, so you may be okay with the standard Tombo model testing with this version.
