### ISSUE TITLE
Is a fast5 specification available?

### ISSUE THREAD

**Issue by RaverJay** [nanoporetech/tombo#72]
Hey,

see subject line. Googling only turns up basic hdf5 tutorials, but where is a comprehensive reference of what should and could be in a fast5 file?

Judging from

https://github.com/nanoporetech/fast5_research/blob/master/fast5_research/fast5.py
`Line 535:  #   Why do we have a specification?`

there seems to be one. Any help appreciated!

Cheers

**Comment by marcus1487** [comment]
Specification can be found [here](https://community.nanoporetech.com/technical_documents/data-analysis/v/datd_5000_v1_revj_22aug2016/read-fast5-files-from-th) for the raw FAST5 format and [here](https://community.nanoporetech.com/technical_documents/data-analysis/v/datd_5000_v1_revj_22aug2016/basecalled-fast5-files) for the basecalled format (both links require community login).

Tombo writes back to the FAST5s in a new group under the main `Analysis` group. The specification  for the Tombo group can be found [here](https://nanoporetech.github.io/tombo/resquiggle.html#tombo-fast5-format).

**Comment by RaverJay** [comment]
Great, thanks!

**Comment by RaverJay** [comment]
Reopening for a followup question:

The fast5 specification is very vague. I was wondering if the raw signal data written to fast5 during sequencing are always current values in picoAmpere?

We see values of about 800 for our direct RNA sequencing runs, but here for example the values are much lower:
https://www.nature.com/articles/nmeth.4577/figures/1

Our median_before open pore values are reasonable at about 260

Sorry that this is rather off-topic and thanks in advance

**Comment by marcus1487** [comment]
These are are 16-bit data acquisition (DAQ or sometimes DAC) values that come straight from the instrument. These come along with several measured variables (offset, digitization and range) to convert to "raw" picoampere units. You can see the conversion from DAQ values to pA in the Tombo code [here](https://github.com/nanoporetech/tombo/blob/1.3/tombo/tombo_stats.py#L293). 

Note though that raw pA values are not all that comparable between reads (see supp. figure 10 from [nanoraw pre-print](https://www.biorxiv.org/content/early/2017/04/10/094672)) and thus a sequence-dependent conversion to scale the signal to better match the modeled pA level is generally performed after raw pA normalization.

Also note that pA normalization is not used in Tombo (code remains for legacy and testing purposes) in favor of median normalization, which generally produced more comparable signal levels across reads as a first pass, though a sequence-based correction factor is still applied to these levels in Tombo in order to obtain the most consistent signal levels between reads.

**Comment by RaverJay** [comment]
Great, huge thanks!
