### ISSUE TITLE
subset reads used during modification detection

### ISSUE THREAD

**Issue by phiweger** [nanoporetech/tombo#76]
Is there a setting so that Tombo explicitly only considers certain reads (based on ID) in the modification detection? 

Use case: I have a transcriptome as reference, but only want to allow reads in the analysis that match across the entire transcript, not shorter fragments.

Thank you.

**Comment by marcus1487** [comment]
There is not a command line utility for this right now, but if you were willing to dig into some python code you could put together a custom reads filter. Here is the [q-socre filtering function](https://github.com/nanoporetech/tombo/blob/1.3/tombo/tombo_helper.py#L749) in the code. Hopefully this function is relatively straightforward. Access to some of the functions called here (`load_index_data`, `write_index_file `, etc) will require importing the `tombo_helper` module. Then you would just need to change the criterion from a q-score threshold to some other criteria. Unfortunately, the `read_id` is not stored in the Tombo index, but it could be extracted with the following bit of code:

```
with h5py.File(rd.fn, 'r') as fast5_data:
    read_id = tombo_herlper.get_raw_read_slot(fast5_data).attrs.get('read_id')
```

I will also note that this procedure will become much easier in the next release which includes a major re-write of the Tombo API along with full documentation and examples for procedures such as this example.

**Comment by phiweger** [comment]
Thank you. I will for now resort to subset the fast5 files and resquiggle only those. Do you have a timeline for the next release?

**Comment by marcus1487** [comment]
I am hoping to get the next release out in the next week or two. Starting to tidy it up right now (and maybe squeeze another feature/improvement in there!).

**Comment by marcus1487** [comment]
This obviously took a bit longer than 1 or 2 weeks, but here we are... the RNA re-squiggle improvements proved to be a bit of a larger task.

In any case, this task should again be much more concise in the current release. For this use case, you can copy pretty closely the [clear filters function](https://github.com/nanoporetech/tombo/blob/1.4/tombo/_filter_reads.py#L29), but instead of replacing the `filtered` with `False` you would replace it with that `rd.read_id in valid_read_ids`. This is assuming that you have a set of read_ids stored in the `valid_read_ids` object. Then simply save the index ([`reads_index.write_index_file()`](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_helper.TomboReads.write_index_file)) and you can process these reads with any other Tombo commands.

You could also use the [`readData`](https://nanoporetech.github.io/tombo/tombo.html#tombo.tombo_helper.readData) objects themselves to extract your filtering criteria. Do note here if you have trouble using the interface for this task.
