### ISSUE TITLE
Question on --signal-matching-score for resquiggle

### ISSUE THREAD

**Issue by phiweger** [nanoporetech/tombo#79]
The default for RNA is 1.3

I currently set it to 2 to not filter 90 % of my reads. 

What are insane values of `--signal-matching-score`, i.e. is 2 already too high to give viable results?

Thank you.

**Comment by marcus1487** [comment]
2 is not an unreasonable number. I noted in the [docs](https://nanoporetech.github.io/tombo/filtering.html#filter-raw-signal-matching) that reasonable range for this value might be 0.5 to 3. But I do think that processing reads above the default threshold should be done with caution. For some reference, here is the distribution of scores from an in vitro transcribed sample (testing a range of bandwidth parameters here; as described [here](https://github.com/nanoporetech/tombo/issues/28#issuecomment-365759599)).

![image](https://user-images.githubusercontent.com/13755444/42093720-35696a98-7b62-11e8-930e-256e16b901db.png)

We will continue to try to improve the robustness of the re-squiggle procedure in order to hopefully rescue these reads failing in this manner.

**Comment by phiweger** [comment]
Thank you for your answer. Since you refer to the recommended range of values in the docs (sorry, must have overread it) I'll close this issue.
