### ISSUE TITLE
OverflowError: cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by btemperton** [nanoporetech/tombo#80]
Hi there,
I'm running a conda installed version of tombo and getting the following error during modification detection:

`tombo detect_modifications de_novo --fast5-basedirs ../fast5/ \
    --statistics-file-basename sample.de_novo_modified_base_detection \
    --per-read-statistics-basename sample.de_novo_modified_base_detection \
    --processes 32 2>&1 | tee -a $LOGFILE`

Error:

`Traceback (most recent call last):
  File "/gpfs/ts0/projects/Research_Project-172179/tools/anaconda3/envs/nanopore/lib/python3.6/multiprocessing/queues.py", line 241, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/gpfs/ts0/projects/Research_Project-172179/tools/anaconda3/envs/nanopore/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
OverflowError: cannot serialize a bytes object larger than 4 GiB`

Any ideas what is trying to serialise a 4Gb object?

**Comment by marcus1487** [comment]
Yes. This is most likely either from 1) a relatively large genome or 2) a very high coverage region computing per-read statistics and passing these back to the main thread (via `mutliprocess.Queue`).

If this is a large genome issue, then this is due to a [known design flaw](https://github.com/nanoporetech/tombo#known-issues) in the main statistics file output. If this is a relatively large genome, and the error is occurring at the very end of the run, then this is probably the case. I will have a fix for this issue in the next release (hopefully in the next week or two). But as a non-ideal work-around until then you can process the reads in chunks using the `filter genome_locations` command as noted in the known issues suggestion on the main github page (link above).

If this is not a particularly large genome size, then there are 2 strategies for fixing this issue depending on the nature of the data:

1. If the sample has very "spike-y" coverage, then the [level coverage](https://nanoporetech.github.io/tombo/filtering.html#filter-level-coverage) filter can be applied to selectively downsample reads in order to obtain more uniform coverage over the whole sample (this filter can also be applied iteratively to continue removing reads). You can get a sense for whether there are large spikes in coverage by looking at the Tombo read pileup, available from the [`tombo text_output browser_files` command](https://nanoporetech.github.io/tombo/text_output.html#text-output-browser-files).
2. If the whole sample is high coverage, then you would have to lower the `--multiprocess-region-size` option (in order to process smaller batches at a time).

It is also possible that this is something else altogether! But do let me know if you solve your issue with one of these strategies. I am also hopeful that the next release will be much more robust to this type of error.

**Comment by lpryszcz** [comment]
Had similar issue, using one process and `--multiprocess-region-size 1000` helped.
