### ISSUE TITLE
Resquiggle on Tombo 1.3 failing 90% of reads - only 28% failed on older version of Tombo

### ISSUE THREAD

**Issue by cweldo00** [nanoporetech/tombo#82]
I have just recently updated my Tombo to the latest version.  I started by using the resquiggle command on old data to make sure all was ok, and actually thought the rate would improve.  However its drastically worse.  I am using the same files fast5 and the same FASTA file as before.  What could be the problem?  I have attached the resquiggle reports from the old version and now with the new version. I see majority of the reads are failing due to "poor raw to expected signal matching".  Has this threshold changed in the newer version?

Older version - analysed in March 2018
![resquiggle report pass](https://user-images.githubusercontent.com/32604538/42142505-a8ddb9b0-7da7-11e8-9652-0ebb8850bd67.jpeg)

New version - analysed July 2018
![resquiggle report pass tombo 1-3](https://user-images.githubusercontent.com/32604538/42142517-c3369dae-7da7-11e8-8ad6-2ff34ef41ac7.jpeg)

**Comment by marcus1487** [comment]
Thank you for raising this issue. This threshold was lowered with the 1.3 release, but this lowering was due to these scores generally lowering in our internal validation data sets due to improvements in the re-squiggle algorithm and signal scaling. We are working on some new features for the re-squiggle algorithm to make the results more robust to a wide range of RNA samples that will hopefully resolve a this poor signal matching occurring in a number of user runs. We hope to have this release out in the next week or two. Hopefully you will see improved results with this next release.
