### ISSUE TITLE
Exposing minimap2 parameters?

### ISSUE THREAD

**Issue by RaverJay** [nanoporetech/tombo#83]
Hey,

it might be worthwhile to expose minimap2 parameters to the user in future versions. Much depends on the mapping accuracy and it could be helpful to fine tune the mapping especially for directRNA data.

Cheers

**Comment by marcus1487** [comment]
Tombo can take a minimap2 index file (instead of a reference fasta) for re-squiggling. The `k` (k-mer length) and `w` (window size) parameters used to create this minimap2 index will [override the Tombo preset values](https://github.com/nanoporetech/tombo/issues/28#issuecomment-366001729). This should give at least some control over the mapping parameters.

Additionally, the re-squiggle algorithm only uses the alignment to extract the relevant bit of genomic/transcriptomic sequence, so an alignment with many indels/mismatches should not effect the results as long as the correct mapping location is determined accurately. I think that the `k` and `w` mapping parameters should contain the majority of the effect for this part of the alignment process.

One other note is that I have not wanted to open the full parameter settings for minimap2 in Tombo as Tombo currently does not (and likely won't) accept spliced mapping ([as discussed here](https://nanoporetech.github.io/tombo/rna.html)). In order to avoid users obtaining poor results from attempting to process such spliced mappings, I have chosen to close the parameter values to minimap2. 

All that being said, if there are particular parameters that would be helpful in processing data more accurately I would certainly be open to adding access to these parameters to the command line interface. You can test out alterations to the minimap2 parameters in Tombo, but this currently requires making edits to the code and re-installing ([as described here](https://github.com/nanoporetech/tombo/issues/28#issuecomment-387200458)).

I hope this helps!
