### ISSUE TITLE
RNA signal is reversed compared to fastq output

### ISSUE THREAD

**Issue by haotianteng** [nanoporetech/tombo#9]
Signal is reversed in RNA sequencing.

**Comment by haotianteng** [comment]
Or is it already supported?

**Comment by haotianteng** [comment]
The RNA sequence fast5 signal seems to be reversed(but not complemented) compared to the output fastq file. Have checked several RNA sequencing results, the event all reversed.
![signalreverserna](https://user-images.githubusercontent.com/11155295/33976722-ab8c2276-e0e2-11e7-9f70-ac2a7370b0ec.png)

**Comment by marcus1487** [comment]
Yes, RNA reads are supported and an RNA model is supplied with Tombo. 

The events are indeed reversed compared to the output fastq. This is because RNA reads are processed 3’ to 5’ by the physical pore. Thus the raw signal is reversed compared to the output fastq as well. Since event level data is still linked to the signal data it seems best to leave this data in sequencing time order.

Hopefully this clears up your issue.

**Comment by haotianteng** [comment]
Great! So this is the normal situation, and a direct use of tombo on these RNA fast5 files would be fine, is it?

**Comment by marcus1487** [comment]
Yes. I am currently auto-detecting the sample type (DNA or RNA) and using the detected model accordingly. In the release to come shortly `resquiggle` will print the model it has chosen and I hope to add flags to explicitly set the sample type in the future (noted as an internal todo).
