### ISSUE TITLE
stat on runs resquiggled on different genome

### ISSUE THREAD

**Issue by DelphIONe** [nanoporetech/tombo#93]
Hi,

Is it possible to detected modification in using 2 runs but each one resquiggled with a different genome ?

Thanks for your reply,

**Comment by marcus1487** [comment]
I am not sure I completely understand this question. Are you looking to compare these two samples from different genomes in some way (sample comparison method)? Or are you simply trying to detect modifications within these samples separately?

**Comment by DelphIONe** [comment]
with sample comparison method. If the comparison is done on the kmers, it should be ok but the result is by genome position, so I think that the answer is no but... 
Sorry if my question seems stupid.

**Comment by marcus1487** [comment]
Ah I see. I think the short answer would be that this is not possible currently. I am not exactly sure how this test would be carried out, since there are many sites for each k-mer over each genome. This may be related to #25, but I am just not sure what the informative output from these types of analyses/comparisons would be.

**Comment by DelphIONe** [comment]
Thanks for your help Marcus.
